function m(b,a,c,d,e){b.i.qb(b.tb,a,c,d,e)}function n(b,a,c,d){b.i.ea?m(b,a,c,d):b.i.$e()._OnMessageFromDOM({type:"event",component:b.tb,handler:a,dispatchOpts:d||null,data:c,responseId:null})}function q(b,a,c){b.i.B(b.tb,a,c)}function v(b,a){for(const [c,d]of a)q(b,c,d)}function w(b){b.$b||(b.i.Hc(b.qe),b.$b=!0)}function aa(b){b.$b&&(b.i.Pd(b.qe),b.$b=!1)}window.kb=class{constructor(b,a){this.i=b;this.tb=a;this.$b=!1;this.qe=()=>this.Ia()}zd(){}Ia(){}};
window.Mf=class{constructor(){this.ud=-1}l(){-1!==this.ud&&(self.clearTimeout(this.ud),this.ud=-1)}};"use strict";class ba{constructor(b){this.Xa=b;this.$c=!1;this.hd=!0;this.xb=this.ta=this.vd=-1}}
function ca(b,a){const c=a.elementId,d=b.wc(c,a),e=new ba(d);b.za.set(c,e);d.style.boxSizing="border-box";d.style.display="none";e.hd=!!a.isVisible;var f=b.Kc(d);f.addEventListener("focus",()=>{x(b,"elem-focused",c)});f.addEventListener("blur",()=>{x(b,"elem-blurred",c)});f=a.htmlIndex;e.vd=f;e.xb=a.htmlZIndex;b.Ma&&(a=b.i.yc(f),e.ta=a,b.i.Ob(a).appendChild(d))}function y(b,a,c){q(b,a,d=>{const e=z(b,d.elementId);return c(e,d)})}
function z(b,a){b=b.za.get(a);if(!b)throw Error(`no element with id ${a}`);return b.Xa}function x(b,a,c,d){d||(d={});d.elementId=c;m(b,a,d)}
window.Nb=class extends self.kb{constructor(b,a){super(b,a);this.za=new Map;this.Ma=!0;v(this,[["create",c=>ca(this,c)],["destroy",c=>{c=c.elementId;const d=z(this,c);this.Ed(d);this.Ma&&d.parentElement.removeChild(d);this.za.delete(c)}],["set-visible",c=>{if(this.Ma){var d=this.za.get(c.elementId),e=d.Xa;d.$c?e.style.display=c.isVisible?"":"none":d.hd=!!c.isVisible}}],["update-position",c=>{if(this.Ma){var d=this.za.get(c.elementId),e=d.Xa,f=this.i;e.style.left=c.left+"px";e.style.top=c.top+"px";
e.style.width=c.width+"px";e.style.height=c.height+"px";var g=c.fontSize;null!==g&&(e.style.fontSize=g+"em");g=c.htmlIndex;d.vd=g;g=f.yc(g);g!==d.ta&&(e.remove(),f.Ob(g).appendChild(e),d.ta=g,f.Tc());c=c.htmlZIndex;c!==d.xb&&(d.xb=c,f.Tc());d.$c||(d.$c=!0,d.hd&&(e.style.display=""))}}],["update-state",c=>{const d=z(this,c.elementId);this.Sb(d,c)}],["focus",c=>this.Qc(c)],["set-css-style",c=>{const d=z(this,c.elementId),e=c.prop;c=c.val;e.startsWith("--")?d.style.setProperty(e,c):d.style[e]=c}],["set-attribute",
c=>{z(this,c.elementId).setAttribute(c.name,c.val)}],["remove-attribute",c=>{z(this,c.elementId).removeAttribute(c.name)}]]);y(this,"get-element",c=>c)}wc(){throw Error("required override");}Ed(){}Sb(){throw Error("required override");}Kc(b){return b}Qc(b){const a=this.Kc(z(this,b.elementId));b.focus?a.focus():a.blur()}};"use strict";const da=/(iphone|ipod|ipad|macos|macintosh|mac os x)/i.test(navigator.userAgent),A=/android/i.test(navigator.userAgent);let ea=0;
function fa(b){const a=document.createElement("script");a.async=!1;a.type="module";return b.Cf?new Promise(c=>{const d="c3_resolve_"+ea;++ea;self[d]=c;a.textContent=b.Gf+`\n\nself["${d}"]();`;document.head.appendChild(a)}):new Promise((c,d)=>{a.onload=c;a.onerror=d;a.src=b;document.head.appendChild(a)})}
async function ha(){if(!navigator.userActivation||"undefined"===typeof OffscreenCanvas)return!1;try{let b=!1;const a=new Worker(URL.createObjectURL(new Blob(['\n\tself.addEventListener("message", () =>\n\t{\n\t\ttry {\n\t\t\tconst offscreenCanvas = new OffscreenCanvas(32, 32);\n\t\t\tconst gl = offscreenCanvas.getContext("webgl");\n\t\t\tself.postMessage(!!gl);\n\t\t}\n\t\tcatch (err)\n\t\t{\n\t\t\tconsole.warn("Feature detection worker error:", err);\n\t\t\tself.postMessage(false);\n\t\t}\n\t});'],{type:"text/javascript"})),
{get type(){b=!0}}),c=await new Promise(d=>{a.addEventListener("message",e=>{a.terminate();d(e.data)});a.postMessage("")});return b&&c}catch(b){return console.warn("Error feature detecting worker mode: ",b),!1}}let B=new Audio;
const ia={"audio/webm; codecs=opus":!!B.canPlayType("audio/webm; codecs=opus"),"audio/ogg; codecs=opus":!!B.canPlayType("audio/ogg; codecs=opus"),"audio/webm; codecs=vorbis":!!B.canPlayType("audio/webm; codecs=vorbis"),"audio/ogg; codecs=vorbis":!!B.canPlayType("audio/ogg; codecs=vorbis"),"audio/mp4":!!B.canPlayType("audio/mp4"),"audio/mpeg":!!B.canPlayType("audio/mpeg")};B=null;async function ja(b){b=await ka(b);return(new TextDecoder("utf-8")).decode(b)}
function ka(b){return new Promise((a,c)=>{const d=new FileReader;d.onload=e=>a(e.target.result);d.onerror=e=>c(e);d.readAsArrayBuffer(b)})}const la=[];let C=0;window.RealFile=window.File;const E=[],ma=new Map,na=new Map;let oa=0;const pa=[];self.runOnStartup=function(b){if("function"!==typeof b)throw Error("runOnStartup called without a function");pa.push(b)};const ta=new Set(["cordova","playable-ad","instant-games"]);let ua=!1;
window.ra=class b{constructor(a){this.ea=a.If;this.Ca=null;this.aa="";this.fb=a.Ff;this.Lb={};this.Za=this.ya=null;this.Wa=[];this.oa=null;this.de=!0;this.M=[];this.od=[];this.pd=!1;this.re=()=>this.Ye();this.dd=!1;this.Yd=0;this.zb=null;this.eb=-1;this.xf=()=>this.jf();this.Ib=new Set;this.wd=null;this.se=[];this.u=a.te;this.ac="file"===location.protocol.substr(0,4);if("playable-ad"===this.u||"instant-games"===this.u)this.ea=!1;if("cordova"===this.u&&this.ea&&A){const c=/Chrome\/(\d+)/i.exec(navigator.userAgent);
c&&90<=parseInt(c[1],10)||(this.ea=!1)}this.qa()?self.chrome.webview.addEventListener("message",c=>this.Od(c.data)):"macos-wkwebview"===this.u&&(self.C3WrapperOnMessage=c=>this.Od(c));this.dc=this.va=null;"html5"!==this.u||window.isSecureContext||console.warn("[Construct] Warning: the browser indicates this is not a secure context. Some features may be unavailable. Use secure (HTTPS) hosting to ensure all features are available.");this.B("canvas","update-size",c=>this.nf(c));this.B("canvas","set-html-layer-count",
c=>this._OnSetHTMLLayerCount(c));this.B("canvas","cleanup-html-layers",()=>this.df());this.B("runtime","cordova-fetch-local-file",c=>this.ef(c));this.B("runtime","create-job-worker",()=>this.ff());this.B("runtime","send-wrapper-extension-message",c=>this.mf(c));"cordova"===this.u?document.addEventListener("deviceready",()=>this.Md(a)):this.Md(a)}l(){this.Ic();this.Ca&&(this.Ca=this.Ca.onmessage=null);this.ya&&(this.ya.terminate(),this.ya=null);this.Za&&(this.Za.l(),this.Za=null);for(const {canvas:a,
ib:c}of this.M)a.remove(),c.remove();this.M.length=0}Fd(){return this.M[0].canvas}yc(a){return Math.min(a,this.M.length-1)}Ob(a){if(0>a||a>=this.M.length)throw new RangeError("invalid canvas layer");return this.M[a].ib}Oe(){return da&&"cordova"===this.u}ob(){const a=navigator.userAgent;return da&&ta.has(this.u)||navigator.standalone||/crios\/|fxios\/|edgios\//i.test(a)}Me(){return A}Dc(){return A&&ta.has(this.u)}Hd(){return"windows-webview2"===this.u||!!("preview"===this.u&&window.chrome&&window.chrome.webview&&
window.chrome.webview.postMessage)}qa(){return this.Hd()||"xbox-uwp-webview2"===this.u}async Md(a){this.ea&&!await ha()&&(this.ea=!1);"macos-wkwebview"===this.u?this.Ja({type:"ready"}):this.qa()&&(this.qf(),this.se=(await this.cf()).registeredComponentIds);if("playable-ad"===this.u){this.va=self.c3_base64files;this.dc={};await this.Ve();for(let d=0,e=a.hb.length;d<e;++d){var c=a.hb[d];this.dc.hasOwnProperty(c)?a.hb[d]={Cf:!0,Gf:this.dc[c]}:this.va.hasOwnProperty(c)&&(a.hb[d]=URL.createObjectURL(this.va[c]))}a.uc=
[]}if("nwjs"===this.u&&self.nw&&self.nw.App.manifest["c3-steam-mode"]){let d=0;this.Hc(()=>{d++;document.body.style.opacity=0===d%2?"1":"0.999"})}a.Ef?this.aa=a.Ef:(c=location.origin,this.aa=("null"===c?"file:///":c)+location.pathname,c=this.aa.lastIndexOf("/"),-1!==c&&(this.aa=this.aa.substr(0,c+1)));a.Kf&&(this.Lb=a.Kf);c=new MessageChannel;this.Ca=c.port1;this.Ca.onmessage=d=>this._OnMessageFromRuntime(d.data);window.c3_addPortMessageHandler&&window.c3_addPortMessageHandler(d=>this.hf(d));this.zb=
new self.Pe(this);await va(this.zb);"object"===typeof window.StatusBar&&window.StatusBar.hide();if("object"===typeof window.AndroidFullScreen)try{await new Promise((d,e)=>{window.AndroidFullScreen.immersiveMode(d,e)})}catch(d){console.error("Failed to enter Android immersive mode: ",d)}this.ea?await this.bf(a,c.port2):await this.af(a,c.port2)}Lc(a){a=this.Lb.hasOwnProperty(a)?this.Lb[a]:a.endsWith("/workermain.js")&&this.Lb.hasOwnProperty("workermain.js")?this.Lb["workermain.js"]:"playable-ad"===
this.u&&this.va.hasOwnProperty(a)?this.va[a]:a;a instanceof Blob&&(a=URL.createObjectURL(a));return a}async xc(a,c,d){if(a.startsWith("blob:"))return new Worker(a,d);if("cordova"===this.u&&this.ac)return a=await this.Mb(d.Bf?a:this.fb+a),new Worker(URL.createObjectURL(new Blob([a],{type:"application/javascript"})),d);a=new URL(a,c);if(location.origin!==a.origin){a=await fetch(a);if(!a.ok)throw Error("failed to fetch worker script");a=await a.blob();return new Worker(URL.createObjectURL(a),d)}return new Worker(a,
d)}sa(){return Math.max(window.innerWidth,1)}ia(){return Math.max(window.innerHeight,1)}Ld(a){var c=this.aa,d=location.href,e=this.sa(),f=this.ia(),g=window.devicePixelRatio,h=b.nb(),k=a.Qf,l=window.cr_previewImageBlobs||this.va,p=window.cr_previewProjectFileBlobs,r=window.cr_previewProjectFiles,t=window.cr_swClientId||"";a=a.te;var u=(new URLSearchParams(self.location.search)).has("debug"),D=this.zb;return{runtimeBaseUrl:c,previewUrl:d,windowInnerWidth:e,windowInnerHeight:f,devicePixelRatio:g,isFullscreen:h,
projectData:k,previewImageBlobs:l,previewProjectFileBlobs:p,previewProjectFileSWUrls:r,swClientId:t,exportType:a,isDebug:u,ife:!!self.Pf,jobScheduler:{inputPort:D.cd,outputPort:D.nd,maxNumWorkers:D.uf},supportedAudioFormats:ia,opusWasmScriptUrl:window.cr_opusWasmScriptUrl||this.fb+"opus.wasm.js",opusWasmBinaryUrl:window.cr_opusWasmBinaryUrl||this.fb+"opus.wasm.wasm",isFileProtocol:this.ac,isiOSCordova:this.Oe(),isiOSWebView:this.ob(),isWindowsWebView2:this.Hd(),isAnyWebView2Wrapper:this.qa(),wrapperComponentIds:this.se,
isFBInstantAvailable:"undefined"!==typeof self.FBInstant}}async bf(a,c){const d=this.Lc(a.Jf);"preview"===this.u?(this.ya=new Worker("previewworker.js",{type:"module",name:"Runtime"}),await new Promise((l,p)=>{const r=t=>{this.ya.removeEventListener("message",r);t.data&&"ok"===t.data.type?l():p()};this.ya.addEventListener("message",r);this.ya.postMessage({type:"construct-worker-init","import":(new URL(d,this.aa)).toString()})})):this.ya=await this.xc(d,this.aa,{type:"module",name:"Runtime",Bf:!0});
const e=document.createElement("canvas");e.style.display="none";const f=e.transferControlToOffscreen();document.body.appendChild(e);const g=document.createElement("div");g.className="c3htmlwrap";document.body.appendChild(g);this.M.push({canvas:e,ib:g});window.c3canvas=e;self.C3_InsertHTMLPlaceholders&&self.C3_InsertHTMLPlaceholders();let h=a.uc||[],k=a.hb;h=await Promise.all(h.map(l=>this.Ta(l)));k=await Promise.all(k.map(l=>this.Ta(l)));if("cordova"===this.u)for(let l=0,p=a.tc.length;l<p;++l){const r=
a.tc[l],t=r[0];if(t===a.xd||"scriptsInEvents.js"===t||t.endsWith("/scriptsInEvents.js"))r[1]=await this.Ta(t)}this.ya.postMessage(Object.assign(this.Ld(a),{type:"init-runtime",isInWorker:!0,messagePort:c,canvas:f,workerDependencyScripts:h,engineScripts:k,projectScripts:a.tc,mainProjectScript:a.xd,projectScriptsStatus:self.C3_ProjectScriptsStatus}),[c,f,...wa(this.zb)]);this.Wa=E.map(l=>new l(this));this.Kd();xa(e);ya(g);za(this.oa);self.c3_callFunction=(l,p)=>{var r=this.oa;return r.i.Id(r.tb,"js-invoke-function",
{name:l,params:p})};"preview"===this.u&&(self.goToLastErrorScript=()=>this.qb("runtime","go-to-last-error-script"))}async af(a,c){const d=document.createElement("canvas");d.style.display="none";document.body.appendChild(d);var e=document.createElement("div");e.className="c3htmlwrap";document.body.appendChild(e);this.M.push({canvas:d,ib:e});window.c3canvas=d;self.C3_InsertHTMLPlaceholders&&self.C3_InsertHTMLPlaceholders();this.Wa=E.map(h=>new h(this));this.Kd();xa(d);ya(e);e=a.hb.map(h=>"string"===
typeof h?(new URL(h,this.aa)).toString():h);if(Array.isArray(a.uc)){var f=[...a.uc].map(h=>h instanceof Blob?URL.createObjectURL(h):h);e.unshift(...f)}e=await Promise.all(e.map(h=>this.Ta(h)));await Promise.all(e.map(h=>fa(h)));e=self.C3_ProjectScriptsStatus;f=a.xd;const g=a.tc;for(let [h,k]of g)if(k||(k=h),h===f)try{k=await this.Ta(k),await fa(k),"preview"!==this.u||e[h]||this.Qd(h,"main script did not run to completion")}catch(l){this.Qd(h,l)}else if("scriptsInEvents.js"===h||h.endsWith("/scriptsInEvents.js"))k=
await this.Ta(k),await fa(k);"preview"===this.u&&"object"!==typeof self.Lf.Nf?(this.Ub(),console.error("[C3 runtime] Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax."),alert("Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax.")):(a=Object.assign(this.Ld(a),{isInWorker:!1,messagePort:c,canvas:d,runOnStartupFunctions:pa}),za(this.oa),this.Nd(),this.Za=self.C3_CreateRuntime(a),await self.C3_InitRuntime(this.Za,
a))}Qd(a,c){this.Ub();console.error(`[Preview] Failed to load project main script (${a}): `,c);alert(`Failed to load project main script (${a}). Check all your JavaScript code has valid syntax. Press F12 and check the console for error details.`)}Nd(){this.Ub()}Ub(){const a=window.cr_previewLoadingElem;a&&(a.parentElement.removeChild(a),window.cr_previewLoadingElem=null)}async ff(){const a=await Aa(this.zb);return{outputPort:a,transferables:[a]}}nf(a){if(!this.dd){var c=a.styleWidth+"px",d=a.styleHeight+
"px",e=a.marginLeft+"px",f=a.marginTop+"px";for(const {canvas:g,ib:h}of this.M)g.style.width=c,g.style.height=d,g.style.marginLeft=e,g.style.marginTop=f,h.style.width=c,h.style.height=d,h.style.marginLeft=e,h.style.marginTop=f,this.de&&(g.style.display="",h.style.display="");document.documentElement.style.setProperty("--construct-scale",a.displayScale);this.de=!1}}_OnSetHTMLLayerCount(a){var c=a.count,d=a.immediate,e=a.styleWidth+"px",f=a.styleHeight+"px";const g=a.marginLeft+"px",h=a.marginTop+"px";
a=[];const k=[];if(c<this.M.length)for(;this.M.length>c;){const {canvas:l,ib:p}=this.M.pop();p.remove();this.ea&&!d?this.od.push(l):l.remove()}else if(c>this.M.length)for(let l=0,p=c-this.M.length;l<p;++l)c=document.createElement("canvas"),c.classList.add("c3overlay"),this.ea?(d=c.transferControlToOffscreen(),a.push(d),k.push(d)):a.push(c),document.body.appendChild(c),d=document.createElement("div"),d.classList.add("c3htmlwrap","c3overlay"),document.body.appendChild(d),c.style.width=e,c.style.height=
f,c.style.marginLeft=g,c.style.marginTop=h,d.style.width=e,d.style.height=f,d.style.marginLeft=g,d.style.marginTop=h,xa(c),ya(d),this.M.push({canvas:c,ib:d});for(const l of this.Wa)if(l instanceof window.Nb&&l.Ma)for(const p of l.za.values())e=l.i.yc(p.vd),f=p.ta,-1!==e&&-1!==f&&e!==f&&(f=p.Xa,f.remove(),l.i.Ob(e).appendChild(f),p.ta=e);this.Tc();return{addedCanvases:a,transferables:k}}df(){for(const a of this.od)a.remove();this.od.length=0}Tc(){this.pd||(this.pd=!0,this.Hc(this.re))}Ye(){this.Pd(this.re);
this.pd=!1;let a=[];for(var c of this.Wa)if(c instanceof window.Nb){var d=c.Ma?[...c.za.values()]:null;d&&a.push(...d)}a.sort((g,h)=>{const k=g.ta,l=h.ta;return k!==l?k-l:g.xb-h.xb});let e=d=c=0,f=a.length;for(;e<f;++e){const g=a[e];g.ta!==c&&(this.Jd(c,a.slice(d,e)),c=g.ta,d=e)}d<e&&this.Jd(c,a.slice(d,e))}Jd(a,c){if(!(1>=c.length||a>=this.M.length)){c=c.map(k=>k.Xa);var d=new Set(c);a=this.Ob(a);for(var e=Array.from(a.children).filter(k=>d.has(k)),f=0,g=Math.min(c.length,e.length);f<g&&c[f]===e[f];++f);
for(var h=f;h<g;++h)e[h].remove();for(h=f;h<g;++h)a.appendChild(c[h])}}$e(){if(this.ea)throw Error("not available in worker mode");return this.Za}qb(a,c,d,e,f){this.Ca.postMessage({type:"event",component:a,handler:c,dispatchOpts:e||null,data:d,responseId:null},f)}Id(a,c,d,e,f){const g=oa++,h=new Promise((k,l)=>{na.set(g,{resolve:k,reject:l})});this.Ca.postMessage({type:"event",component:a,handler:c,dispatchOpts:e||null,data:d,responseId:g},f);return h}_OnMessageFromRuntime(a){const c=a.type;if("event"===
c)return this.gf(a);if("result"===c)this.kf(a);else if("runtime-ready"===c)this.lf();else if("alert-error"===c)this.Ub(),alert(a.message);else if("creating-runtime"===c)this.Nd();else throw Error(`unknown message '${c}'`);}gf(a){const c=a.component,d=a.handler,e=a.data,f=a.responseId;if(a=ma.get(c))if(a=a.get(d)){var g=null;try{g=a(e)}catch(h){console.error(`Exception in '${c}' handler '${d}':`,h);null!==f&&this.Tb(f,!1,""+h);return}if(null===f)return g;g&&g.then?g.then(h=>this.Tb(f,!0,h)).catch(h=>
{console.error(`Rejection from '${c}' handler '${d}':`,h);this.Tb(f,!1,""+h)}):this.Tb(f,!0,g)}else console.warn(`[DOM] No handler '${d}' for component '${c}'`);else console.warn(`[DOM] No event handlers for component '${c}'`)}Tb(a,c,d){let e;d&&d.transferables&&(e=d.transferables);this.Ca.postMessage({type:"result",responseId:a,isOk:c,result:d},e)}kf(a){const c=a.responseId,d=a.isOk;a=a.result;const e=na.get(c);d?e.resolve(a):e.reject(a);na.delete(c)}B(a,c,d){let e=ma.get(a);e||(e=new Map,ma.set(a,
e));if(e.has(c))throw Error(`[DOM] Component '${a}' already has handler '${c}'`);e.set(c,d)}static Ra(a){if(E.includes(a))throw Error("DOM handler already added");E.push(a)}Kd(){for(const a of this.Wa)if("runtime"===a.tb){this.oa=a;return}throw Error("cannot find runtime DOM handler");}hf(a){this.qb("debugger","message",a)}lf(){for(const a of this.Wa)a.zd()}static nb(){return!!(document.fullscreenElement||document.webkitFullscreenElement||document.mozFullScreenElement||ua)}static Vb(a){ua=!!a}Hc(a){this.Ib.add(a);
this.Sc()}Pd(a){this.Ib.delete(a);0===this.Ib.size&&this.Ic()}Sc(){-1===this.eb&&0<this.Ib.size&&(this.eb=requestAnimationFrame(this.xf))}Ic(){-1!==this.eb&&(cancelAnimationFrame(this.eb),this.eb=-1)}jf(){this.eb=-1;for(const a of this.Ib)a();this.Sc()}ba(a){this.oa.ba(a)}ha(a){this.oa.ha(a)}Rc(){this.oa.Rc()}Rb(a){this.oa.Rb(a)}Ne(){return!!ia["audio/webm; codecs=opus"]}async rf(a){a=await this.Id("runtime","opus-decode",{arrayBuffer:a},null,[a]);return new Float32Array(a)}Re(a){this.dd=!0;this.Yd=
a}Le(a){return/^(?:[a-z\-]+:)?\/\//.test(a)||"data:"===a.substr(0,5)||"blob:"===a.substr(0,5)}Gd(a){return!this.Le(a)}async Ta(a){return"cordova"===this.u&&(a.startsWith("file:")||this.ac&&this.Gd(a))?(a.startsWith(this.aa)&&(a=a.substr(this.aa.length)),a=await this.Mb(a),URL.createObjectURL(new Blob([a],{type:"application/javascript"}))):a}async ef(a){const c=a.filename;switch(a.as){case "text":return await this.Ke(c);case "buffer":return await this.Mb(c);default:throw Error("unsupported type");
}}Cd(a){const c=window.cordova.file.applicationDirectory+"www/"+a;return new Promise((d,e)=>{window.resolveLocalFileSystemURL(c,f=>{f.file(d,e)},e)})}async Ke(a){a=await this.Cd(a);return await ja(a)}Jc(){if(la.length&&!(8<=C)){C++;var a=la.shift();this.We(a.filename,a.Hf,a.Af)}}Mb(a){return new Promise((c,d)=>{la.push({filename:a,Hf:e=>{C--;this.Jc();c(e)},Af:e=>{C--;this.Jc();d(e)}});this.Jc()})}async We(a,c,d){try{const e=await this.Cd(a),f=await ka(e);c(f)}catch(e){d(e)}}Od(a){if("entered-fullscreen"===
a)b.Vb(!0),G(this.oa);else if("exited-fullscreen"===a)b.Vb(!1),G(this.oa);else if("object"===typeof a){const c=a.type;"wrapper-init-response"===c?(this.wd(a),this.wd=null):"extension-message"===c?this.qb("runtime","wrapper-extension-message",a):console.warn("Unknown wrapper message: ",a)}else console.warn("Unknown wrapper message: ",a)}mf(a){this.Ja({type:"extension-message",componentId:a.componentId,messageId:a.messageId,params:a.params||[],asyncId:a.asyncId})}Ja(a){this.qa()?window.chrome.webview.postMessage(JSON.stringify(a)):
"macos-wkwebview"===this.u&&window.webkit.messageHandlers.C3Wrapper.postMessage(JSON.stringify(a))}qf(){window.moveTo=(a,c)=>{this.Ja({type:"set-window-position",windowX:Math.ceil(a),windowY:Math.ceil(c)})};window.resizeTo=(a,c)=>{this.Ja({type:"set-window-size",windowWidth:Math.ceil(a),windowHeight:Math.ceil(c)})}}cf(){return this.qa()?new Promise(a=>{this.wd=a;this.Ja({type:"wrapper-init"})}):Promise.resolve()}async Ve(){const a=[];for(const [c,d]of Object.entries(this.va))a.push(this.Ue(c,d));
await Promise.all(a)}async Ue(a,c){if("object"===typeof c)this.va[a]=new Blob([c.str],{type:c.type}),this.dc[a]=c.str;else{let d=await this.Ze(c);d||(d=this.Xe(c));this.va[a]=d}}async Ze(a){try{return await (await fetch(a)).blob()}catch(c){return console.warn("Failed to fetch a data: URI. Falling back to a slower workaround. This is probably because the Content Security Policy unnecessarily blocked it. Allow data: URIs in your CSP to avoid this.",c),null}}Xe(a){a=this.pf(a);return this.Te(a.data,
a.Df)}pf(a){var c=a.indexOf(",");if(0>c)throw new URIError("expected comma in data: uri");var d=a.substring(c+1);c=a.substring(5,c).split(";");a=c[0]||"";const e=c[2];d="base64"===c[1]||"base64"===e?atob(d):decodeURIComponent(d);return{Df:a,data:d}}Te(a,c){var d=a.length;let e=d>>2,f=new Uint8Array(d),g=new Uint32Array(f.buffer,0,e),h,k;for(k=h=0;h<e;++h)g[h]=a.charCodeAt(k++)|a.charCodeAt(k++)<<8|a.charCodeAt(k++)<<16|a.charCodeAt(k++)<<24;for(d&=3;d--;)f[k]=a.charCodeAt(k),++k;return new Blob([f],
{type:c})}};"use strict";const H=self.ra,Ba=new Map([["OSLeft","MetaLeft"],["OSRight","MetaRight"]]),I={dispatchRuntimeEvent:!0,dispatchUserScriptEvent:!0},Ca={dispatchUserScriptEvent:!0},Da={dispatchRuntimeEvent:!0};function Ea(b){return new Promise((a,c)=>{const d=document.createElement("link");d.onload=()=>a(d);d.onerror=e=>c(e);d.rel="stylesheet";d.href=b;document.head.appendChild(d)})}function Fa(b){return new Promise((a,c)=>{const d=new Image;d.onload=()=>a(d);d.onerror=e=>c(e);d.src=b})}
async function J(b){b=URL.createObjectURL(b);try{return await Fa(b)}finally{URL.revokeObjectURL(b)}}function Ga(b){return new Promise((a,c)=>{let d=new FileReader;d.onload=e=>a(e.target.result);d.onerror=e=>c(e);d.readAsText(b)})}
async function Ha(b,a,c){if(!/firefox/i.test(navigator.userAgent))return await J(b);var d=await Ga(b);d=(new DOMParser).parseFromString(d,"image/svg+xml");const e=d.documentElement;if(e.hasAttribute("width")&&e.hasAttribute("height")){const f=e.getAttribute("width"),g=e.getAttribute("height");if(!f.includes("%")&&!g.includes("%"))return await J(b)}e.setAttribute("width",a+"px");e.setAttribute("height",c+"px");d=(new XMLSerializer).serializeToString(d);b=new Blob([d],{type:"image/svg+xml"});return await J(b)}
function Ia(b){do{if(b.parentNode&&b.hasAttribute("contenteditable"))return!0;b=b.parentNode}while(b);return!1}const Ja=new Set(["input","textarea","datalist","select"]),Ka=new Set(["canvas","body","html"]);function K(b){b.target.tagName&&Ka.has(b.target.tagName.toLowerCase())&&b.preventDefault()}function La(b){b.target.tagName&&b.target.classList.contains("c3htmlwrap")&&b.preventDefault()}function Ma(b){(b.metaKey||b.ctrlKey)&&b.preventDefault()}
self.C3_GetSvgImageSize=async function(b){b=await J(b);if(0<b.width&&0<b.height)return[b.width,b.height];b.style.position="absolute";b.style.left="0px";b.style.top="0px";b.style.visibility="hidden";document.body.appendChild(b);const a=b.getBoundingClientRect();document.body.removeChild(b);return[a.width,a.height]};self.C3_RasterSvgImageBlob=async function(b,a,c,d,e){b=await Ha(b,a,c);const f=document.createElement("canvas");f.width=d;f.height=e;f.getContext("2d").drawImage(b,0,0,a,c);return f};
let Na=!1;document.addEventListener("pause",()=>Na=!0);document.addEventListener("resume",()=>Na=!1);function xa(b){b.addEventListener("selectstart",K);b.addEventListener("gesturehold",K);b.addEventListener("pointerdown",K)}function ya(b){b.addEventListener("selectstart",La);b.addEventListener("gesturehold",La);b.addEventListener("touchstart",La)}function za(b){b.Xd=!0;b.jd=b.i.sa();b.Ab=b.i.ia()}
function G(b){if(!b.ma){var a=H.nb();a&&"any"!==b.sd&&Oa(b);m(b,"fullscreenchange",{isFullscreen:a,innerWidth:b.sa(),innerHeight:b.ia()})}}async function Pa(b){await Promise.all(b.webfonts.map(async a=>{a=new FontFace(a.name,`url('${a.url}')`);document.fonts.add(a);await a.load()}))}
async function Qa(b){var a=b.imageBitmapOpts;b=await self.C3_RasterSvgImageBlob(b.blob,b.imageWidth,b.imageHeight,b.surfaceWidth,b.surfaceHeight);a=a?await createImageBitmap(b,a):await createImageBitmap(b);return{imageBitmap:a,transferables:[a]}}async function Ra(b){return await self.C3_GetSvgImageSize(b.blob)}function Sa(b){window.c3_postToMessagePort&&(b.from="runtime",window.c3_postToMessagePort(b))}
function Ta(b){self.setTimeout(()=>{b.Wd=!0},1E3);"cordova"===b.i.u?(document.addEventListener("pause",()=>Ua(b,!0)),document.addEventListener("resume",()=>Ua(b,!1))):document.addEventListener("visibilitychange",()=>Ua(b,"hidden"===document.visibilityState));b.jc=!("hidden"!==document.visibilityState&&!Na);return{isSuspended:b.jc}}
function Va(b){b.Sd||(b.Sd=!0,window.addEventListener("deviceorientation",a=>{b.ma||m(b,"deviceorientation",{absolute:!!a.absolute,alpha:a.alpha||0,beta:a.beta||0,gamma:a.gamma||0,timeStamp:a.timeStamp,webkitCompassHeading:a.webkitCompassHeading,webkitCompassAccuracy:a.webkitCompassAccuracy},I)}),window.addEventListener("deviceorientationabsolute",a=>{b.ma||m(b,"deviceorientationabsolute",{absolute:!!a.absolute,alpha:a.alpha||0,beta:a.beta||0,gamma:a.gamma||0,timeStamp:a.timeStamp},I)}))}
function Wa(b){b.Rd||(b.Rd=!0,window.addEventListener("devicemotion",a=>{if(!b.ma){var c=null,d=a.acceleration;d&&(c={x:d.x||0,y:d.y||0,z:d.z||0});d=null;var e=a.accelerationIncludingGravity;e&&(d={x:e.x||0,y:e.y||0,z:e.z||0});e=null;var f=a.rotationRate;f&&(e={alpha:f.alpha||0,beta:f.beta||0,gamma:f.gamma||0});m(b,"devicemotion",{acceleration:c,accelerationIncludingGravity:d,rotationRate:e,interval:a.interval,timeStamp:a.timeStamp},I)}}))}async function Xa(b){await Ea(b.url)}
function Ya(b,a){b.Zd=a.message;-1===b.Yc&&(b.Yc=setTimeout(()=>{b.Yc=-1;const c=document.getElementById("exportToVideoMessage");c&&(c.textContent=b.Zd)},250))}function Za(b,a){console.warn("[Construct] Fullscreen request failed: ",a);m(b,"fullscreenerror",{isFullscreen:H.nb(),innerWidth:b.sa(),innerHeight:b.ia()})}
function Ua(b,a){b.jc!==a&&((b.jc=a)?b.i.Ic():b.i.Sc(),m(b,"visibilitychange",{hidden:a}),!a&&b.i.ob()&&(b=()=>{document.scrollingElement.scrollTop=0;document.scrollingElement.scrollLeft=0},setTimeout(b,50),setTimeout(b,100),setTimeout(b,250),setTimeout(b,500)))}
function $a(b,a,c){"Backspace"===c.key&&K(c);if(b.i.qa()){var d=["r","p","f","g","u"];(["F3","F5","F7"].includes(c.key)||c.ctrlKey&&d.includes(c.key))&&c.preventDefault()}b.ma||(d=Ba.get(c.code)||c.code,n(b,a,{code:d,key:c.key,which:c.which,repeat:c.repeat,altKey:c.altKey,ctrlKey:c.ctrlKey,metaKey:c.metaKey,shiftKey:c.shiftKey,timeStamp:c.timeStamp},I))}
function L(b,a,c,d){b.ma||c.sourceCapabilities&&c.sourceCapabilities.firesTouchEvents||c.originalEvent&&c.originalEvent.sourceCapabilities&&c.originalEvent.sourceCapabilities.firesTouchEvents||n(b,a,{button:c.button,buttons:c.buttons,clientX:c.clientX,clientY:c.clientY+b.Fa,pageX:c.pageX,pageY:c.pageY+b.Fa,movementX:c.movementX||0,movementY:c.movementY||0,timeStamp:c.timeStamp},d)}
function M(b,a,c){if(!b.ma){var d=0;"mouse"===c.pointerType&&(d=b.ld);n(b,a,{pointerId:c.pointerId,pointerType:c.pointerType,button:c.button,buttons:c.buttons,lastButtons:d,clientX:c.clientX,clientY:c.clientY+b.Fa,pageX:c.pageX,pageY:c.pageY+b.Fa,movementX:c.movementX||0,movementY:c.movementY||0,width:c.width||0,height:c.height||0,pressure:c.pressure||0,tangentialPressure:c.tangentialPressure||0,tiltX:c.tiltX||0,tiltY:c.tiltY||0,twist:c.twist||0,timeStamp:c.timeStamp},I);"mouse"===c.pointerType&&
(b.ld=c.buttons)}}function ab(b,a,c){document.body.style.position="";document.body.style.overflow="";document.body.style.transform="";b.Fa=0;if(0<c){var d=document.activeElement;d&&(d=d.getBoundingClientRect(),a=(d.top+d.bottom)/2-(a-c)/2,a>c&&(a=c),0>a&&(a=0),0<a&&(document.body.style.position="absolute",document.body.style.overflow="visible",document.body.style.transform=`translateY(${-a}px)`,b.Fa=a))}}
function bb(b,a,c,d){const e=b.sa(),f=b.ia();b.gb=-1;e!=a||f!=c?m(b,"window-resize",{innerWidth:e,innerHeight:f,devicePixelRatio:window.devicePixelRatio,isFullscreen:H.nb()}):10>d&&cb(b,e,f,d+1)}function cb(b,a,c,d){-1!==b.gb&&clearTimeout(b.gb);b.gb=setTimeout(()=>bb(b,a,c,d),48)}
function Oa(b){b=b.sd;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(b).catch(a=>console.warn("[Construct] Failed to lock orientation: ",a));else try{let a=!1;screen.lockOrientation?a=screen.lockOrientation(b):screen.webkitLockOrientation?a=screen.webkitLockOrientation(b):screen.mozLockOrientation?a=screen.mozLockOrientation(b):screen.msLockOrientation&&(a=screen.msLockOrientation(b));a||console.warn("[Construct] Failed to lock orientation")}catch(a){console.warn("[Construct] Failed to lock orientation: ",
a)}}function db(b){return!b||b===document||b===window||b===document.body||"canvas"===b.tagName.toLowerCase()}
H.Ra(class extends self.kb{constructor(b){super(b,"runtime");this.Xd=!1;this.gb=-1;this.sd="any";this.jc=this.Rd=this.Sd=!1;this.pc=document.createElement("div");this.pc.className="c3-screen-reader-text";this.pc.setAttribute("aria-live","polite");document.body.appendChild(this.pc);this.Na=null;this.ma=!1;this.Zd="";this.Yc=-1;this.Wd=!1;this.jd=b.sa();this.Ab=b.ia();this.Fa=this.Kb=0;b.B("runtime","invoke-download",c=>{const d=c.url;c=c.filename;const e=document.createElement("a"),f=document.body;
e.textContent=c;e.href=d;e.download=c;f.appendChild(e);e.click();f.removeChild(e)});b.B("runtime","load-webfonts",c=>Pa(c));b.B("runtime","raster-svg-image",c=>Qa(c));b.B("runtime","get-svg-image-size",c=>Ra(c));b.B("runtime","set-target-orientation",c=>{this.sd=c.targetOrientation});b.B("runtime","register-sw",()=>{window.C3_RegisterSW&&window.C3_RegisterSW()});b.B("runtime","post-to-debugger",c=>Sa(c));b.B("runtime","go-to-script",c=>Sa(c));b.B("runtime","before-start-ticking",()=>Ta(this));b.B("runtime",
"debug-highlight",c=>{if(c.show){this.Na||(this.Na=document.createElement("div"),this.Na.id="inspectOutline",document.body.appendChild(this.Na));var d=this.Na;d.style.display="";d.style.left=c.left-1+"px";d.style.top=c.top-1+"px";d.style.width=c.width+2+"px";d.style.height=c.height+2+"px";d.textContent=c.name}else this.Na&&(this.Na.style.display="none")});b.B("runtime","enable-device-orientation",()=>Va(this));b.B("runtime","enable-device-motion",()=>Wa(this));b.B("runtime","add-stylesheet",c=>Xa(c));
b.B("runtime","script-create-worker",c=>{const d=c.port2;(new Worker(c.url,c.opts)).postMessage({type:"construct-worker-init",port2:d},[d])});b.B("runtime","alert",c=>this.Oc(c));b.B("runtime","screen-reader-text",c=>{var d=c.type;"create"===d?(d=document.createElement("p"),d.id="c3-sr-"+c.id,d.textContent=c.text,this.pc.appendChild(d)):"update"===d?(d=document.getElementById("c3-sr-"+c.id))?d.textContent=c.text:console.warn(`[Construct] Missing screen reader text with id ${c.id}`):"release"===d?
(d=document.getElementById("c3-sr-"+c.id))?d.remove():console.warn(`[Construct] Missing screen reader text with id ${c.id}`):console.warn(`[Construct] Unknown screen reader text update '${d}'`)});b.B("runtime","hide-cordova-splash",()=>{navigator.splashscreen&&navigator.splashscreen.hide&&navigator.splashscreen.hide()});b.B("runtime","set-exporting-to-video",c=>{this.ma=!0;const d=document.createElement("h1");d.id="exportToVideoMessage";d.textContent=c.message;document.body.prepend(d);document.body.classList.add("exportingToVideo");
this.i.Fd().style.display="";this.i.Re(c.duration)});b.B("runtime","export-to-video-progress",c=>Ya(this,c));b.B("runtime","exported-to-video",c=>{window.zf({type:"exported-video",arrayBuffer:c.arrayBuffer,contentType:c.contentType,time:c.time})});b.B("runtime","exported-to-image-sequence",c=>{window.zf({type:"exported-image-sequence",blobArr:c.blobArr,time:c.time,gif:c.gif})});const a=new Set(["input","textarea","datalist"]);window.addEventListener("contextmenu",c=>{const d=c.target;a.has(d.tagName.toLowerCase())||
Ia(d)||c.preventDefault()});window.addEventListener("selectstart",K);window.addEventListener("gesturehold",K);window.addEventListener("touchstart",K,{passive:!1});window.addEventListener("pointerdown",K,{passive:!1});this.ld=0;window.addEventListener("mousedown",c=>{1===c.button&&c.preventDefault()});window.addEventListener("mousewheel",Ma,{passive:!1});window.addEventListener("wheel",Ma,{passive:!1});window.addEventListener("resize",()=>{a:{if(!this.ma&&this.Xd){var c=this.sa();var d=this.ia();if(this.i.Dc()){if(this.Wd){if(this.jd===
c&&d<this.Ab){this.Kb=this.Ab-d;ab(this,this.Ab,this.Kb);c=void 0;break a}0<this.Kb&&(this.Kb=0,ab(this,d,this.Kb))}this.jd=c;this.Ab=d}m(this,"window-resize",{innerWidth:c,innerHeight:d,devicePixelRatio:window.devicePixelRatio,isFullscreen:H.nb()});this.i.ob()&&(-1!==this.gb&&clearTimeout(this.gb),bb(this,c,d,0))}c=void 0}return c});window.addEventListener("fullscreenchange",()=>G(this));window.addEventListener("webkitfullscreenchange",()=>G(this));window.addEventListener("mozfullscreenchange",()=>
G(this));window.addEventListener("fullscreenerror",c=>Za(this,c));window.addEventListener("webkitfullscreenerror",c=>Za(this,c));window.addEventListener("mozfullscreenerror",c=>Za(this,c));if(b.ob()){if(window.visualViewport){let c=Infinity;window.visualViewport.addEventListener("resize",()=>{const d=window.visualViewport.height;d>c&&(document.scrollingElement.scrollTop=0,document.scrollingElement.scrollLeft=0);c=d})}else window.addEventListener("focusout",()=>{{const e=document.activeElement;if(e){var c=
e.tagName.toLowerCase();var d=new Set("email number password search tel text url".split(" "));c="textarea"===c?!0:"input"===c?d.has(e.type.toLowerCase()||"text"):Ia(e)}else c=!1}c||(document.scrollingElement.scrollTop=0)});document.documentElement.setAttribute("ioswebview","")}this.$a=new Set;this.fc=new WeakSet;this.Ba=!1}zd(){window.addEventListener("focus",()=>{m(this,"window-focus",null,Da)});window.addEventListener("blur",()=>{try{var a=window.parent&&window.parent.document.hasFocus()}catch(c){a=
!1}m(this,"window-blur",{parentHasFocus:a},Da);this.ld=0});window.addEventListener("focusin",a=>{a=a.target;(Ja.has(a.tagName.toLowerCase())||Ia(a))&&m(this,"keyboard-blur",null,Da)});window.addEventListener("keydown",a=>$a(this,"keydown",a));window.addEventListener("keyup",a=>$a(this,"keyup",a));window.addEventListener("mousedown",a=>L(this,"mousedown",a,Ca));window.addEventListener("mousemove",a=>L(this,"mousemove",a,Ca));window.addEventListener("mouseup",a=>L(this,"mouseup",a,Ca));window.addEventListener("dblclick",
a=>L(this,"dblclick",a,I));window.addEventListener("wheel",a=>{this.ma||m(this,"wheel",{clientX:a.clientX,clientY:a.clientY+this.Fa,pageX:a.pageX,pageY:a.pageY+this.Fa,deltaX:a.deltaX,deltaY:a.deltaY,deltaZ:a.deltaZ,deltaMode:a.deltaMode,timeStamp:a.timeStamp},I)});window.addEventListener("pointerdown",a=>{window!==window.top&&window.focus();db(a.target)&&document.activeElement&&!db(document.activeElement)&&document.activeElement.blur();M(this,"pointerdown",a)});this.i.ea&&"undefined"!==typeof window.onpointerrawupdate&&
self===self.top?window.addEventListener("pointerrawupdate",a=>{M(this,"pointermove",a)}):window.addEventListener("pointermove",a=>M(this,"pointermove",a));window.addEventListener("pointerup",a=>M(this,"pointerup",a));window.addEventListener("pointercancel",a=>M(this,"pointercancel",a));const b=()=>this.Rc();window.addEventListener("pointerup",b,!0);window.addEventListener("touchend",b,!0);window.addEventListener("click",b,!0);window.addEventListener("keydown",b,!0);window.addEventListener("gamepadconnected",
b,!0);this.i.Me()&&!this.i.Dc()&&navigator.virtualKeyboard&&(navigator.virtualKeyboard.overlaysContent=!0,navigator.virtualKeyboard.addEventListener("geometrychange",()=>{ab(this,this.ia(),navigator.virtualKeyboard.boundingRect.height)}));this.i.ob()&&(document.scrollingElement.scrollTop=0,document.scrollingElement.scrollLeft=0)}sa(){return this.i.sa()}ia(){return this.i.ia()}Rc(){var b=[...this.$a];this.$a.clear();if(!this.Ba)for(const a of b)(b=a.play())&&b.catch(()=>{this.fc.has(a)||this.$a.add(a)})}ba(b){if("function"!==
typeof b.play)throw Error("missing play function");this.fc.delete(b);let a;try{a=b.play()}catch(c){this.$a.add(b);return}a&&a.catch(()=>{this.fc.has(b)||this.$a.add(b)})}ha(b){this.$a.delete(b);this.fc.add(b)}Rb(b){this.Ba=!!b}Oc(b){alert(b.message)}});"use strict";
async function va(b){if(b.sf)throw Error("already initialised");b.sf=!0;var a=b.Da.Lc(("playable-ad"===b.Da.u?b.Da.fb:"")+"dispatchworker.js");b.Xc=await b.Da.xc(a,b.sb,{name:"DispatchWorker"});a=new MessageChannel;b.cd=a.port1;b.Xc.postMessage({type:"_init","in-port":a.port2},[a.port2]);b.nd=await Aa(b)}function wa(b){return[b.cd,b.nd]}
async function Aa(b){const a=b.ee.length;var c=b.Da.Lc(("playable-ad"===b.Da.u?b.Da.fb:"")+"jobworker.js");c=await b.Da.xc(c,b.sb,{name:"JobWorker"+a});const d=new MessageChannel,e=new MessageChannel;b.Xc.postMessage({type:"_addJobWorker",port:d.port1},[d.port1]);c.postMessage({type:"init",number:a,"dispatch-port":d.port2,"output-port":e.port2},[d.port2,e.port2]);b.ee.push(c);return e.port1}
self.Pe=class{constructor(b){this.Da=b;this.sb=b.aa;this.sb="preview"===b.u?this.sb+"workers/":this.sb+b.fb;this.uf=Math.min(navigator.hardwareConcurrency||2,16);this.Xc=null;this.ee=[];this.nd=this.cd=null}};"use strict";window.C3_Is_Supported&&(window.c3_runtimeInterface=new self.ra({If:!0,Jf:"workermain.js",hb:["scripts/c3runtime.js"],tc:[],xd:"",Ff:"scripts/",uc:[],te:"html5"}));"use strict";
self.ra.Ra(class extends self.kb{constructor(b){super(b,"mouse");v(this,[["cursor",a=>{document.documentElement.style.cursor=a}],["request-pointer-lock",()=>{this.i.Fd().requestPointerLock()}],["release-pointer-lock",()=>{document.exitPointerLock()}]]);document.addEventListener("pointerlockchange",()=>{m(this,"pointer-lock-change",{"has-pointer-lock":!!document.pointerLockElement})});document.addEventListener("pointerlockerror",()=>{m(this,"pointer-lock-error",{"has-pointer-lock":!!document.pointerLockElement})})}});
"use strict";function eb(){}function fb(b){window.C3_RegisterSW&&window.OfflineClientInfo&&window.OfflineClientInfo.SetMessageCallback(a=>m(b,"sw-message",a.data))}
function gb(b){b=b.orientation;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(b).catch(a=>console.warn("[Construct] Failed to lock orientation: ",a));else try{let a=!1;screen.lockOrientation?a=screen.lockOrientation(b):screen.webkitLockOrientation?a=screen.webkitLockOrientation(b):screen.mozLockOrientation?a=screen.mozLockOrientation(b):screen.msLockOrientation&&(a=screen.msLockOrientation(b));a||console.warn("[Construct] Failed to lock orientation")}catch(a){console.warn("[Construct] Failed to lock orientation: ",
a)}}
self.ra.Ra(class extends self.kb{constructor(b){super(b,"browser");this.u="";v(this,[["get-initial-state",a=>{this.u=a.exportType;return{location:location.toString(),isOnline:!!navigator.onLine,referrer:document.referrer,title:document.title,isCookieEnabled:!!navigator.cookieEnabled,screenWidth:screen.width,screenHeight:screen.height,windowOuterWidth:window.outerWidth,windowOuterHeight:window.outerHeight,isConstructArcade:"undefined"!==typeof window.is_scirra_arcade}}],["ready-for-sw-messages",()=>
fb(this)],["alert",a=>this.Oc(a)],["close",()=>{navigator.app&&navigator.app.exitApp?navigator.app.exitApp():navigator.device&&navigator.device.exitApp?navigator.device.exitApp():window.close()}],["set-focus",a=>this.Qc(a)],["vibrate",a=>{navigator.vibrate&&navigator.vibrate(a.pattern)}],["lock-orientation",a=>gb(a)],["unlock-orientation",()=>{try{screen.orientation&&screen.orientation.unlock?screen.orientation.unlock():screen.unlockOrientation?screen.unlockOrientation():screen.webkitUnlockOrientation?
screen.webkitUnlockOrientation():screen.mozUnlockOrientation?screen.mozUnlockOrientation():screen.msUnlockOrientation&&screen.msUnlockOrientation()}catch(a){}}],["navigate",a=>{var c=a.type;if("back"===c)navigator.app&&navigator.app.backHistory?navigator.app.backHistory():window.history.back();else if("forward"===c)window.history.forward();else if("reload"===c)location.reload();else if("url"===c){c=a.url;const d=a.target;a=a.exportType;self.cordova&&self.cordova.InAppBrowser?self.cordova.InAppBrowser.open(c,
"_system"):"preview"===a||this.i.qa()?window.open(c,"_blank"):this.Of||(2===d?window.top.location=c:1===d?window.parent.location=c:window.location=c)}else"new-window"===c&&(c=a.url,a=a.tag,self.cordova&&self.cordova.InAppBrowser?self.cordova.InAppBrowser.open(c,"_system"):window.open(c,a))}],["request-fullscreen",a=>{if(this.i.qa()||"macos-wkwebview"===this.u)self.ra.Vb(!0),this.i.Ja({type:"set-fullscreen",fullscreen:!0});else{const c={navigationUI:"auto"};a=a.navUI;1===a?c.navigationUI="hide":2===
a&&(c.navigationUI="show");a=document.documentElement;let d;a.requestFullscreen?d=a.requestFullscreen(c):a.mozRequestFullScreen?d=a.mozRequestFullScreen(c):a.msRequestFullscreen?d=a.msRequestFullscreen(c):a.webkitRequestFullScreen&&(d="undefined"!==typeof Element.ALLOW_KEYBOARD_INPUT?a.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT):a.webkitRequestFullScreen());d instanceof Promise&&d.catch(eb)}}],["exit-fullscreen",()=>{if(this.i.qa()||"macos-wkwebview"===this.u)self.ra.Vb(!1),this.i.Ja({type:"set-fullscreen",
fullscreen:!1});else{let a;document.exitFullscreen?a=document.exitFullscreen():document.mozCancelFullScreen?a=document.mozCancelFullScreen():document.msExitFullscreen?a=document.msExitFullscreen():document.webkitCancelFullScreen&&(a=document.webkitCancelFullScreen());a instanceof Promise&&a.catch(eb)}}],["set-hash",a=>{location.hash=a.hash}],["set-document-css-style",a=>{const c=a.prop,d=a.value;var e=a.selector;a=a["is-all"];try{if(e)if(a)var f=Array.from(document.querySelectorAll(e));else{var g=
document.querySelector(e);f=g?[g]:[]}else f=[document.documentElement];e=f;for(const h of e)c.startsWith("--")?h.style.setProperty(c,d):h.style[c]=d}catch(h){console.warn("[Browser] Failed to set style: ",h)}}],["get-document-css-style",a=>{{const d=a.prop;a=a.selector;try{const e=document.querySelector(a);var c=e?{isOk:!0,result:window.getComputedStyle(e).getPropertyValue(d)}:{isOk:!1}}catch(e){console.warn("[Browser] Failed to get style: ",e),c={isOk:!1}}}return c}],["set-window-size",a=>{window.resizeTo(a.windowWidth,
a.windowHeight)}],["set-window-position",a=>{window.moveTo(a.windowX,a.windowY)}]]);window.addEventListener("online",()=>{m(this,"online-state",{isOnline:!0})});window.addEventListener("offline",()=>{m(this,"online-state",{isOnline:!1})});window.addEventListener("hashchange",()=>{m(this,"hashchange",{location:location.toString()})});document.addEventListener("backbutton",()=>{m(this,"backbutton")})}Oc(b){alert(b.message)}Qc(b){b=b.isFocus;if("nwjs"===this.u){const a="nwjs"===this.u?nw.Window.get():
null;b?a.focus():a.blur()}else b?window.focus():window.blur()}});"use strict";async function hb(b,a){b.fd=a.isInWorker;a=document.createElement("video");b.qc=!!a.requestVideoFrameCallback&&!b.i.Dc();const c=!!self.createImageBitmap;b.Hb=b.fd||c;return{postImageBitmaps:b.Hb,supportedFormats:{"video/webm":!!a.canPlayType("video/webm"),"video/mp4":!!a.canPlayType("video/mp4")}}}
async function ib(b,a){if(!b.Wc.has(a)){a.c3_rvfcId=a.requestVideoFrameCallback(()=>ib(b,a));try{const c=a.c3_sequenceNumber++,d=await createImageBitmap(a);c>a.c3_lastFrameSequence&&(a.c3_imageBitmap=d,a.c3_lastFrameSequence=c)}catch(c){}}}function N(b,a,c,d){b.Wc.has(a)||x(b,"playback-event",c,{type:d})}
self.ra.Ra(class extends self.Nb{constructor(b){super(b,"video");this.Hb=this.qc=this.fd=this.Ma=!1;this.hc=this.yf=0;this.Wc=new WeakSet;q(this,"init",a=>hb(this,a));y(this,"play",a=>{this.ba(a)});y(this,"pause",a=>{this.ha(a);a.pause()});y(this,"set-source",(a,c)=>{a.src=c.src;a.load()});y(this,"set-playback-time",(a,c)=>{try{a.currentTime=c.time}catch(d){console.error("[Video] Exception setting playback time: ",d)}});y(this,"set-playback-rate",(a,c)=>{try{a.playbackRate=c.rate}catch(d){console.error("[Video] Exception setting playback rate: ",
d)}});y(this,"set-looping",(a,c)=>{a.loop=c.isLooping});y(this,"set-muted",(a,c)=>{a.muted=c.isMuted});y(this,"set-volume",(a,c)=>{a.volume=c.volume});self.C3Video_GetElement=a=>z(this,a)}ba(b){this.i.ba(b);this.Hb&&this.qc&&-1===b.c3_rvfcId&&(b.c3_rvfcId=b.requestVideoFrameCallback(()=>ib(this,b)))}ha(b){this.i.ha(b);this.Hb&&this.qc&&-1!==b.c3_rvfcId&&(b.cancelVideoFrameCallback(b.c3_rvfcId),b.c3_rvfcId=-1)}wc(b,a){const c=document.createElement("video");c.crossOrigin="anonymous";c.playsInline=
!0;c.c3_imageBitmap=null;c.c3_rvfcId=-1;c.c3_sequenceNumber=0;c.c3_lastFrameSequence=-1;c.addEventListener("canplay",()=>N(this,c,b,0));c.addEventListener("canplaythrough",()=>N(this,c,b,1));c.addEventListener("ended",()=>N(this,c,b,2));c.addEventListener("error",()=>N(this,c,b,3));c.addEventListener("loadstart",()=>N(this,c,b,4));c.addEventListener("playing",()=>N(this,c,b,5));c.addEventListener("pause",()=>N(this,c,b,6));c.addEventListener("stalled",()=>N(this,c,b,7));const d=a.autoplay;0===d?(c.autoplay=
!1,c.preload="none"):1===d?(c.autoplay=!1,c.preload="auto"):c.autoplay=!0;a.src&&(c.src=a.src);2===d&&this.ba(c);this.hc++;w(this);return c}Sb(){}Ed(b){this.ha(b);b&&!b.paused&&!b.ended&&0<b.currentTime&&b.pause();b.src="";this.hc=Math.max(this.hc-1,0);0===this.hc&&aa(this);this.Wc.add(b)}Ia(){const b={},a={sequenceNumber:this.yf++,videoData:b},c=[],d=[];for(const [e,f]of this.za.entries()){const g=f.Xa,h={currentTime:g.currentTime,playbackRate:g.playbackRate,duration:g.duration,videoWidth:g.videoWidth,
videoHeight:g.videoHeight};if(this.Hb)if(this.qc){const k=g.c3_imageBitmap;g.c3_imageBitmap=null;(h.imageBitmap=k)&&c.push(k)}else d.push(createImageBitmap(g).then(k=>{h.imageBitmap=k;c.push(k)}).catch(()=>{h.imageBitmap=null}));b[e.toString()]=h}Promise.all(d).then(()=>{this.fd?m(this,"state",a,!1,c):n(this,"state",a)})}});"use strict";const lb=180/Math.PI;
async function mb(b,a){if(a.isiOSCordova||a.isSafari)b.lc=!0;b.td=a.timeScaleMode;b.je=["equalpower","HRTF","soundfield"][a.panningModel];b.Vd=["linear","inverse","exponential"][a.distanceModel];b.ke=a.refDistance;b.ie=a.maxDistance;b.me=a.rolloffFactor;if(b.i.dd)b.lc=!0,b.g=new OfflineAudioContext({numberOfChannels:2,sampleRate:48E3,length:Math.ceil(48E3*b.i.Yd)});else{var c={latencyHint:a.latencyHint};b.pe||(c.sampleRate=48E3);if("undefined"!==typeof AudioContext)b.g=new AudioContext(c);else if("undefined"!==
typeof webkitAudioContext)b.g=new webkitAudioContext(c);else throw Error("Web Audio API not supported");nb(b);b.g.onstatechange=()=>{"running"!==b.g.state&&nb(b);m(b,"audiocontext-state",{audioContextState:b.g.state})}}b.Va=b.g.createGain();b.Va.connect(b.g.destination);c=a.listenerPos;b.$[0]=c[0];b.$[1]=c[1];b.$[2]=c[2];b.g.listener.setPosition(c[0],c[1],c[2]);b.g.listener.setOrientation(...b.ca);self.C3_GetAudioContextCurrentTime=()=>b.g.currentTime;try{await Promise.all(a.preloadList.map(d=>O(b,
d.originalUrl,d.url,d.type,!1)))}catch(d){console.error("[Construct] Preloading sounds failed: ",d)}return{sampleRate:b.g.sampleRate,audioContextState:b.g.state,outputLatency:b.g.outputLatency||0}}
async function ob(b,a){var c=a.originalUrl,d=a.url;const e=a.type,f=a.isMusic,g=a.tags,h=a.isLooping,k=a.vol,l=a.pos,p=a.panning,r=a.stereoPan;let t=a.off;0<t&&!a.trueClock&&(b.g.getOutputTimestamp?(a=b.g.getOutputTimestamp(),t=t-a.performanceTime/1E3+a.contextTime):t=t-performance.now()/1E3+b.g.currentTime);b.fe=g.slice(0);pb(b,g);try{b.R=await qb(b,c,d,e,g,f);if(p){P(b.R,!0);var u=b.R,D=p.innerAngle,qa=p.outerAngle,sa=p.outerGain;if(u.yb){rb(u,p.x,p.y,p.z,p.angle);var F=self.jb.Se;u.wa[0]!==F(D)&&
(u.wa[0]=F(D),u.F.coneInnerAngle=F(D));u.wa[1]!==F(qa)&&(u.wa[1]=F(qa),u.F.coneOuterAngle=F(qa));u.wa[2]!==sa&&(u.wa[2]=sa,u.F.coneOuterGain=sa)}p.hasOwnProperty("uid")&&(b.R.ua=p.uid)}else"number"===typeof r&&0!==r?(Q(b.R,!0),sb(b.R,r)):(P(b.R,!1),Q(b.R,!1));b.R.Play(h,k,l,t)}catch(Eb){console.error("[Construct] Audio: error starting playback: ",Eb);return}finally{c=g.join(" ");d=b.Gb.get(c);if(!d)throw Error("expected pending tag");d.yd--;0===d.yd&&(d.resolve(),b.Gb.delete(c))}w(b)}
async function tb(b,a){var c=a.tags;const d=a.vol,e=a.duration;a=a.stopOnEnd;await ub(b,c);for(const h of R(b,c))if(!h.Aa){c=h.G.gain;c.cancelScheduledValues(0);var f=h.v.g.currentTime,g=f+e;c.setValueAtTime(c.value,f);c.linearRampToValueAtTime(d,g);h.Qa=d;h.Ya=g;h.oe=a}S(b)}async function vb(b,a){const c=a.tags;a=a.rate;await ub(b,c);for(const d of R(b,c))d.na!==a&&(d.na=a,d.Ka())}async function wb(b,a){const c=a.tags;a=a.pos;await ub(b,c);for(const d of R(b,c))d.Ec(a)}
async function xb(b,a){const c=a.originalUrl,d=a.url,e=a.type;a=a.isMusic;try{await qb(b,c,d,e,"",a)}catch(f){console.error("[Construct] Audio: error preloading: ",f)}}async function yb(b,a){if(a=await O(b,"",a.url,a.type,a.isMusic,!0))a.l(),a=b.ka.indexOf(a),-1!==a&&b.ka.splice(a,1)}
async function zb(b,a){const c=a.type;var d=a.hasOwnProperty("tags")?a.tags:[a.tag];const e=a.params;let f;if("convolution"===c)try{f=await O(b,a.bufferOriginalUrl,a.bufferUrl,a.bufferType,!1)}catch(k){console.log("[Construct] Audio: error loading convolution: ",k);return}for(const k of d){if("filter"===c)d=new self.ze(b,...e);else if("delay"===c)d=new self.xe(b,...e);else if("convolution"===c){var g=d=new self.we(b,f.ja,...e),h=a.bufferType;g.Td=a.bufferOriginalUrl;g.Ud=h}else if("flanger"===c)d=
new self.Ae(b,...e);else if("phaser"===c)d=new self.Ce(b,...e);else if("gain"===c)d=new self.Be(b,...e);else if("stereopan"===c)d=new self.Ee(b,...e);else if("tremolo"===c)d=new self.Fe(b,...e);else if("ringmod"===c)d=new self.De(b,...e);else if("distortion"===c)d=new self.ye(b,...e);else if("compressor"===c)d=new self.ve(b,...e);else if("analyser"===c)d=new self.ue(b,...e);else throw Error("invalid effect type");g=b;h=k;h=h.toLowerCase();let l=g.la.get(h);l||(l=[],g.la.set(h,l));d.ce=l.length;d.rd=
h;l.push(d);Ab(g,h)}Bb(b)}
async function Cb(b,a){const c=a.saveLoadMode;if(3!==c){var d=[];for(var e of b.H)e.Ga()&&1===c||!e.Ga()&&2===c?d.push(e):e.l();b.H=d}for(const f of b.la.values())for(const g of f)g.l();b.la.clear();b.rc=a.timeScale;b.Zc=a.gameTime;d=a.listenerPos;b.$[0]=d[0];b.$[1]=d[1];b.$[2]=d[2];b.g.listener.setPosition(d[0],d[1],d[2]);d=a.listenerOrientation;if(Array.isArray(d)){for(e=0;6>e;++e)b.ca[e]=d[e];b.g.listener.setOrientation(...b.ca)}b.Ba=a.isSilent;b.i.Rb(b.Ba);b.ec=a.masterVolume;b.Va.gain.value=
b.ec;d=[];for(const f of Object.values(a.effects))d.push(Promise.all(f.map(g=>zb(b,g))));await Promise.all(d);await Promise.all(a.playing.map(f=>Db(b,f,c)));S(b)}
async function Fb(b,a){try{const c=b.g.suspend(a.time);b.be?b.g.resume():(b.g.startRendering().then(d=>{const e=[];for(let f=0,g=d.numberOfChannels;f<g;++f){const h=d.getChannelData(f);e.push(h.buffer)}b.i.qb("runtime","offline-audio-render-completed",{duration:d.duration,length:d.length,numberOfChannels:d.numberOfChannels,sampleRate:d.sampleRate,channelData:e},null,e)}).catch(d=>Gb(d)),b.be=!0);await c}catch(c){Gb(c)}}
function nb(b){b.Zb||(b.bd=!1,window.addEventListener("pointerup",b.Ea,!0),window.addEventListener("touchend",b.Ea,!0),window.addEventListener("click",b.Ea,!0),window.addEventListener("keydown",b.Ea,!0),b.Zb=!0)}
async function O(b,a,c,d,e,f){for(var g of b.ka)if(g.mb()===c)return await Hb(g),g;if(f)return null;if(e&&(b.lc||b.ae)){f=0;for(let h=0,k=b.ka.length;h<k;++h)g=b.ka[h],b.ka[f]=g,g.Ga()?g.l():++f;b.ka.length=f}f="audio/webm; codecs=opus"===d&&!b.pe;e&&f&&(b.ae=!0);c=!e||b.lc||f?new self.Ie(b,a,c,d,e,f):new self.Ge(b,a,c,d,e);b.ka.push(c);await Hb(c);b.he.has(a)||(m(b,"buffer-metadata",{originalUrl:a,duration:c.ga()}),b.he.add(a));return c}
function Ib(b,a){return b===a||b.normalize().toLowerCase()===a.normalize().toLowerCase()}function Jb(b,a){return(a=b.la.get(a.toLowerCase()))?a[0].N():b.fa()}function Ab(b,a){a=a.toLowerCase();let c=b.fa();var d=b.la.get(a);if(d&&d.length){c=d[0].N();for(let f=0,g=d.length;f<g;++f){var e=d[f];f+1===g?e.U(b.fa()):e.U(d[f+1].N())}}for(const f of Kb(b,a))d=c,e=f.da||f.F||f.G,e.disconnect(),e.connect(d);b.Oa&&b.kd===a&&(b.Oa.disconnect(),b.Oa.connect(c))}
function*Kb(b,a){if(a)for(const c of b.H)Ib(0<c.pa.length?c.pa[0]:"",a)&&(yield c);else b.R&&!b.R.O()&&(yield b.R)}function Lb(b,a,c){return c?b.i.rf(a).then(d=>{const e=b.g.createBuffer(1,d.length,48E3);e.getChannelData(0).set(d);return e}):new Promise((d,e)=>{b.g.decodeAudioData(a,d,e)})}function Mb(b,a){let c=0;for(let d=0,e=b.H.length;d<e;++d){const f=b.H[d];b.H[c]=f;f.P===a?f.l():++c}b.H.length=c}
function*R(b,a){if(0<a.length)for(const d of b.H){a:{b=d.pa;var c=a;for(const e of c){c=!1;for(const f of b)if(Ib(f,e)){c=!0;break}if(!c){b=!1;break a}}b=!0}b&&(yield d)}else b.R&&!b.R.O()&&(yield b.R)}async function qb(b,a,c,d,e,f){for(const g of b.H)if(g.mb()===c&&(g.vc()||f))return g.pa=e,g;a=await O(b,a,c,d,f);e="html5"===a.Uc?new self.He(a.v,a,e):new self.Je(a.v,a,e);b.H.push(e);return e}
function pb(b,a){a=a.join(" ");let c=b.Gb.get(a);if(!c){let d=null;c={yd:0,promise:new Promise(e=>d=e),resolve:d};b.Gb.set(a,c)}c.yd++}function ub(b,a){return(b=b.Gb.get((0===a.length?b.fe:a).join(" ")))?b.promise:Promise.resolve()}function S(b){if(0<b.Ua.size)w(b);else for(const a of b.H)if(!a.I&&!a.O()){w(b);break}}function Ob(b,a,c,d){m(b,"trigger",{type:a,tags:c,aiid:d})}function Bb(b){b.ed||(b.ed=!0,Promise.resolve().then(()=>Pb(b)))}
function Pb(b){const a={};for(const [c,d]of b.la)a[c]=d.map(e=>e.lb());m(b,"fxstate",{fxstate:a});b.ed=!1}
async function Db(b,a,c){if(3!==c){var d=a.bufferOriginalUrl,e=a.bufferUrl,f=a.bufferType,g=a.isMusic,h=a.tags,k=a.isLooping,l=a.volume,p=a.playbackTime;if(!g||1!==c)if(g||2!==c){c=null;try{c=await qb(b,d,e,f,h,g)}catch(r){console.error("[Construct] Audio: error loading audio state: ",r);return}b=c;(d=a.pan)?(P(b,!0),e=b.F,f=d.pos,b.bb[0]=f[0],b.bb[1]=f[1],b.bb[2]=f[2],f=d.orient,b.ab[0]=f[0],b.ab[1]=f[1],b.ab[2]=f[2],e.setPosition(...b.bb),e.setOrientation(...b.ab),b.wa[0]=d.cia,b.wa[1]=d.coa,b.wa[2]=
d.cog,e.coneInnerAngle=d.cia,e.coneOuterAngle=d.coa,e.coneOuterGain=d.cog,b.ua=d.uid):P(b,!1);b=c;d=a.stereoPan;"number"!==typeof d?Q(b,!1):(Q(b,!0),sb(b,d));c.Play(k,l,p,0);a.isPlaying||c.pb();c.Nc(a)}}}function Gb(b){console.error("[Audio] Offline rendering error: ",b)}
self.jb=class extends self.kb{constructor(b){super(b,"audio");this.Va=this.g=null;this.Zb=this.bd=!1;this.Ea=()=>{if(!this.bd){var a=this.g;"suspended"===a.state&&a.resume&&a.resume();var c=a.createBuffer(1,220,22050),d=a.createBufferSource();d.buffer=c;d.connect(a.destination);d.start(0);"running"===a.state&&this.Zb&&(this.bd=!0,window.removeEventListener("pointerup",this.Ea,!0),window.removeEventListener("touchend",this.Ea,!0),window.removeEventListener("click",this.Ea,!0),window.removeEventListener("keydown",
this.Ea,!0),this.Zb=!1)}};this.ka=[];this.H=[];this.R=null;this.fe=[];this.he=new Set;this.ge=-1;this.Gb=new Map;this.ec=1;this.Ba=!1;this.td=0;this.rc=1;this.Zc=0;this.je="HRTF";this.Vd="inverse";this.ke=600;this.ie=1E4;this.me=1;this.$=[0,0,0];this.ca=[0,0,-1,0,1,0];this.ae=this.lc=!1;this.pe=this.i.Ne();this.la=new Map;this.Ua=new Set;this.be=this.ed=!1;this.kd="";this.Oa=null;self.C3Audio_OnMicrophoneStream=(a,c)=>{this.Oa&&this.Oa.disconnect();this.kd=c.toLowerCase();this.Oa=this.g.createMediaStreamSource(a);
this.Oa.connect(Jb(this,this.kd))};this.Yb=null;self.C3Audio_GetOutputStream=()=>{this.Yb||(this.Yb=this.g.createMediaStreamDestination(),this.Va.connect(this.Yb));return this.Yb.stream};self.C3Audio_DOMInterface=this;v(this,[["create-audio-context",a=>mb(this,a)],["play",a=>ob(this,a)],["stop",a=>{a=a.tags;for(const c of R(this,a))c.Ha()}],["stop-all",()=>{for(const a of this.H)a.Ha()}],["set-paused",a=>{const c=a.tags;a=a.paused;for(const d of R(this,c))a?d.pb():d.Qb();S(this)}],["set-volume",a=>
{const c=a.tags;a=a.vol;for(const d of R(this,c))T(d,a)}],["fade-volume",a=>tb(this,a)],["set-master-volume",a=>{this.ec=a.vol;this.Va.gain.value=this.ec}],["set-muted",a=>{const c=a.tags;a=a.isMuted;for(const d of R(this,c))Qb(d,a)}],["set-silent",a=>{this.Ba=a.isSilent;this.i.Rb(this.Ba);for(const c of this.H)c.Wb()}],["set-looping",a=>{const c=a.tags;a=a.isLooping;for(const d of R(this,c))d.Fc(a)}],["set-playback-rate",a=>vb(this,a)],["set-stereo-pan",a=>{const c=a.tags;a=a.p;for(const d of R(this,
c))Q(d,!0),sb(d,a)}],["seek",a=>wb(this,a)],["preload",a=>xb(this,a)],["unload",a=>yb(this,a)],["unload-all",()=>{for(const a of this.ka)a.l();this.ka.length=0}],["set-suspended",a=>{a=a.isSuspended;!a&&this.g.resume&&this.g.resume();for(const c of this.H)c.Gc(a);a&&this.g.suspend&&this.g.suspend()}],["add-effect",a=>zb(this,a)],["set-effect-param",a=>{var c=a.tags;const d=a.index,e=a.param,f=a.value,g=a.ramp;a=a.time;for(const h of c)c=this.la.get(h.toLowerCase()),!c||0>d||d>=c.length||c[d].Z(e,
f,g,a);Bb(this)}],["remove-effects",a=>{a=a.tags;for(const c of a){a=c.toLowerCase();const d=this.la.get(a);if(!d||!d.length)break;for(const e of d)e.l();this.la.delete(a);Ab(this,a)}}],["tick",a=>{this.rc=a.timeScale;this.Zc=a.gameTime;this.ge=a.tickCount;if(0!==this.td)for(var c of this.H)c.Ka();!(c=a.listenerPos)||this.$[0]===c[0]&&this.$[1]===c[1]&&this.$[2]===c[2]||(this.$[0]=c[0],this.$[1]=c[1],this.$[2]=c[2],this.g.listener.setPosition(c[0],c[1],c[2]));if((c=a.listenerOrientation)&&(this.ca[0]!==
c[0]||this.ca[1]!==c[1]||this.ca[2]!==c[2]||this.ca[3]!==c[3]||this.ca[4]!==c[4]||this.ca[5]!==c[5])){for(let d=0;6>d;++d)this.ca[d]=c[d];this.g.listener.setOrientation(...this.ca)}for(const d of a.instPans){a=d.uid;for(const e of this.H)e.ua===a&&rb(e,d.x,d.y,d.z,d.angle)}}],["load-state",a=>Cb(this,a)],["offline-render-audio",a=>Fb(this,a)],["offline-render-finish",()=>{this.g.resume()}]])}V(){return this.g}fa(){return this.Va}GetAudioContextExtern(){return this.V()}GetDestinationNodeExtern(){return this.fa()}Pb(){return this.Ba}ba(b){this.i.ba(b)}ha(b){this.i.ha(b)}Ia(){for(var b of this.Ua)b.Ia();
b=this.g.currentTime;for(var a of this.H)a.Ia(b);a=this.H.filter(c=>!c.I&&!c.O()).map(c=>c.lb());m(this,"state",{tickCount:this.ge,outputLatency:this.g.outputLatency||0,audioInstances:a,analysers:[...this.Ua].map(c=>({tag:c.rd,index:c.ce,peak:c.cb,rms:c.le,binCount:c.m.frequencyBinCount,freqBins:c.$d}))});0===a.length&&0===this.Ua.size&&aa(this)}static Se(b){return b*lb}static Dd(b){return Math.max(Math.min(Math.pow(10,b/20),1),0)}static Qe(b){return Math.log(Math.max(Math.min(b,1),0))/Math.log(10)*
20}};self.ra.Ra(self.jb);"use strict";function Hb(b){b.cc||(b.cc=b.Mc());return b.cc}self.Ad=class{constructor(b,a,c,d,e){this.v=b;this.wf=a;this.Pa=c;this.T=d;this.tf=e;this.Uc="";this.cc=null}l(){this.cc=this.v=null}Mc(){}V(){return this.v.V()}Ac(){return this.wf}mb(){return this.Pa}zc(){return this.T}Ga(){return this.tf}ga(){}};"use strict";
self.Ge=class extends self.Ad{constructor(b,a,c,d,e){super(b,a,c,d,e);this.Uc="html5";this.L=new Audio;this.L.crossOrigin="anonymous";this.L.autoplay=!1;this.L.preload="auto";this.Bb=this.Cb=null;this.L.addEventListener("canplaythrough",()=>!0);this.Fb=this.V().createGain();this.Eb=null;this.L.addEventListener("canplay",()=>{this.Cb&&(this.Cb(),this.Bb=this.Cb=null);!this.Eb&&this.L&&(this.Eb=this.V().createMediaElementSource(this.L),this.Eb.connect(this.Fb))});this.onended=null;this.L.addEventListener("ended",
()=>{if(this.onended)this.onended()});this.L.addEventListener("error",f=>{console.error(`[Construct] Audio '${this.Pa}' error: `,f);this.Bb&&(this.Bb(f),this.Bb=this.Cb=null)})}l(){Mb(this.v,this);this.Fb.disconnect();this.Fb=null;this.Eb.disconnect();this.Eb=null;this.L&&!this.L.paused&&this.L.pause();this.L=this.onended=null;super.l()}Mc(){return new Promise((b,a)=>{this.Cb=b;this.Bb=a;this.L.src=this.Pa})}W(){return this.L}ga(){return this.L.duration}};"use strict";
async function Rb(b){if(b.La)return b.La;var a=b.v.i;if("cordova"===a.u&&a.Gd(b.Pa)&&a.ac)b.La=await a.Mb(b.Pa);else{a=await fetch(b.Pa);if(!a.ok)throw Error(`error fetching audio data: ${a.status} ${a.statusText}`);b.La=await a.arrayBuffer()}}async function Sb(b){if(b.ja)return b.ja;b.ja=await Lb(b.v,b.La,b.vf);b.La=null}
self.Ie=class extends self.Ad{constructor(b,a,c,d,e,f){super(b,a,c,d,e);this.Uc="webaudio";this.ja=this.La=null;this.vf=!!f}l(){Mb(this.v,this);this.ja=this.La=null;super.l()}async Mc(){try{await Rb(this),await Sb(this)}catch(b){console.error(`[Construct] Failed to load audio '${this.Pa}': `,b)}}ga(){return this.ja?this.ja.duration:0}};"use strict";let Tb=0;
function P(b,a){a=!!a;b.yb!==a&&(b.yb=a,b.yb?(Q(b,!1),b.F||(b.F=b.V().createPanner(),b.F.panningModel=b.v.je,b.F.distanceModel=b.v.Vd,b.F.refDistance=b.v.ke,b.F.maxDistance=b.v.ie,b.F.rolloffFactor=b.v.me),b.G.disconnect(),b.G.connect(b.F),b.F.connect(b.fa())):(b.F.disconnect(),b.G.disconnect(),b.G.connect(b.fa())))}
function Q(b,a){a=!!a;b.bc!==a&&(b.bc=a,b.bc?(P(b,!1),b.da=b.V().createStereoPanner(),b.G.disconnect(),b.G.connect(b.da),b.da.connect(b.fa())):(b.da.disconnect(),b.da=null,b.G.disconnect(),b.G.connect(b.fa())))}function sb(b,a){b.bc&&b.qd!==a&&(b.da.pan.value=a,b.qd=a)}function T(b,a){b.Qa=a;b.G.gain.cancelScheduledValues(0);b.Ya=-1;b.G.gain.value=b.Bc()}function Qb(b,a){a=!!a;b.Aa!==a&&(b.Aa=a,b.Wb())}
function rb(b,a,c,d,e){if(b.yb){var f=b.bb,g=b.ab,h=Math.cos(e);e=Math.sin(e);if(f[0]!==a||f[1]!==c||f[2]!==d)f[0]=a,f[1]=c,f[2]=d,b.F.setPosition(...f);if(g[0]!==h||g[1]!==e||0!==g[2])g[0]=h,g[1]=e,g[2]=0,b.F.setOrientation(...g)}}function U(b){return b.gd?b.v.Zc:performance.now()/1E3}
self.Bd=class{constructor(b,a,c){this.v=b;this.P=a;this.pa=c;this.Xb=Tb++;this.G=this.V().createGain();this.G.connect(this.fa());this.F=null;this.yb=!1;this.bb=[0,0,0];this.ab=[0,0,0];this.wa=[0,0,0];this.da=null;this.bc=!1;this.qd=0;this.I=!0;this.Y=this.xa=this.J=!1;this.Qa=1;this.Aa=!1;this.na=1;b=this.v.td;this.gd=1===b&&!this.Ga()||2===b;this.Ya=this.ua=-1;this.oe=!1}l(){this.P=this.v=null;this.F&&(this.F.disconnect(),this.F=null);this.da&&(this.da.disconnect(),this.da=null);this.G.disconnect();
this.G=null}V(){return this.v.V()}fa(){return Jb(this.v,0<this.pa.length?this.pa[0]:"")}Ac(){return this.P.Ac()}mb(){return this.P.mb()}zc(){return this.P.zc()}Ga(){return this.P.Ga()}O(){}vc(){}IsPlaying(){return!this.I&&!this.J&&!this.O()}Sa(){}ga(){return this.P.ga()}Play(){}Ha(){}pb(){}Qb(){}Ia(b){-1!==this.Ya&&b>=this.Ya&&(this.Ya=-1,this.oe&&this.Ha(),Ob(this.v,"fade-ended",this.pa,this.Xb))}Bc(){const b=this.Qa;return isFinite(b)?b:0}Pb(){return this.v.Pb()}Wb(){}Fc(){}Ka(){}Ec(){}Gc(){}Cc(){}lb(){var b=
this.Xb,a=this.pa,c=this.ga(),d=-1===this.Ya?this.Qa:this.G.gain.value,e=this.IsPlaying();if(this.F){var f=this.F;f={pos:this.bb,orient:this.ab,cia:f.coneInnerAngle,coa:f.coneOuterAngle,cog:f.coneOuterGain,uid:this.ua}}else f=null;return{aiid:b,tags:a,duration:c,volume:d,isPlaying:e,playbackTime:this.Sa(),playbackRate:this.na,uid:this.ua,bufferOriginalUrl:this.Ac(),bufferUrl:"",bufferType:this.zc(),isMusic:this.Ga(),isLooping:this.Y,isMuted:this.Aa,resumePosition:this.Cc(),pan:f,stereoPan:this.da?
this.qd:null}}Nc(b){var a=b.playbackRate;this.na!==a&&(this.na=a,this.Ka());Qb(this,b.isMuted)}};"use strict";
self.He=class extends self.Bd{constructor(b,a,c){super(b,a,c);this.P.Fb.connect(this.G);this.P.onended=()=>this.Pc()}l(){this.Ha();this.P.Fb.disconnect();super.l()}W(){return this.P.W()}Pc(){this.I=!0;this.ua=-1;Ob(this.v,"ended",this.pa,this.Xb)}O(){return this.W().ended}vc(){return this.I?!0:this.O()}Sa(){let b=this.W().currentTime;this.Y||(b=Math.min(b,this.ga()));return b}Play(b,a,c){const d=this.W();1!==d.playbackRate&&(d.playbackRate=1);d.loop!==b&&(d.loop=b);T(this,a);this.Aa=!1;d.muted&&(d.muted=
!1);if(d.currentTime!==c)try{d.currentTime=c}catch(e){console.warn(`[Construct] Exception seeking audio '${this.P.mb()}' to position '${c}': `,e)}this.v.ba(d);this.J=this.I=!1;this.Y=b;this.na=1}Ha(){const b=this.W();b.paused||b.pause();this.v.ha(b);this.I=!0;this.J=!1;this.ua=-1}pb(){if(!(this.J||this.I||this.O())){var b=this.W();b.paused||b.pause();this.v.ha(b);this.J=!0}}Qb(){!this.J||this.I||this.O()||(this.v.ba(this.W()),this.J=!1)}Wb(){this.W().muted=this.Aa||this.Pb()}Fc(b){b=!!b;this.Y!==
b&&(this.Y=b,this.W().loop=b)}Ka(){let b=this.na;this.gd&&(b*=this.v.rc);try{this.W().playbackRate=b}catch(a){console.warn(`[Construct] Unable to set playback rate '${b}':`,a)}}Ec(b){if(!this.I&&!this.O())try{this.W().currentTime=b}catch(a){console.warn(`[Construct] Error seeking audio to '${b}': `,a)}}Cc(){return this.Sa()}Gc(b){b?this.IsPlaying()?(this.W().pause(),this.xa=!0):this.xa=!1:this.xa&&(this.v.ba(this.W()),this.xa=!1)}};"use strict";
function V(b){b.s&&(b.s.onended=null,b.s.disconnect(),b.s.buffer=null);b.s=null;b.rb=null}
self.Je=class extends self.Bd{constructor(b,a,c){super(b,a,c);this.s=null;this.ic=d=>this.Pc(d);this.ad=!0;this.rb=null;this.S=this.kc=this.mc=0;this.md=1}l(){this.Ha();V(this);this.ic=null;super.l()}Pc(b){this.J||this.xa||b.target!==this.rb||(this.I=this.ad=!0,this.ua=-1,V(this),Ob(this.v,"ended",this.pa,this.Xb))}O(){return!this.I&&this.s&&this.s.loop||this.J?!1:this.ad}vc(){return!this.s||this.I?!0:this.O()}Sa(){let b;b=this.J?this.S:this.kc+(U(this)-this.mc)*this.na;this.Y||(b=Math.min(b,this.ga()));
return b}Play(b,a,c,d){this.Aa=!1;this.md=1;T(this,a);V(this);this.s=this.V().createBufferSource();this.s.buffer=this.P.ja;this.s.connect(this.G);this.rb=this.s;this.s.onended=this.ic;this.s.loop=b;this.s.start(d,c);this.J=this.I=this.ad=!1;this.Y=b;this.na=1;this.mc=U(this);this.kc=c}Ha(){if(this.s)try{this.s.stop(0)}catch(b){}this.I=!0;this.J=!1;this.ua=-1}pb(){this.J||this.I||this.O()||(this.S=this.Sa(),this.Y&&(this.S%=this.ga()),this.J=!0,this.s.stop(0))}Qb(){!this.J||this.I||this.O()||(V(this),
this.s=this.V().createBufferSource(),this.s.buffer=this.P.ja,this.s.connect(this.G),this.rb=this.s,this.s.onended=this.ic,this.s.loop=this.Y,T(this,this.Qa),this.Ka(),this.s.start(0,this.S),this.mc=U(this),this.kc=this.S,this.J=!1)}Bc(){return super.Bc()*this.md}Wb(){this.md=this.Aa||this.Pb()?0:1;T(this,this.Qa)}Fc(b){b=!!b;this.Y!==b&&(this.Y=b,this.s&&(this.s.loop=b))}Ka(){let b=this.na;this.gd&&(b*=this.v.rc);this.s&&(this.s.playbackRate.value=b)}Ec(b){this.I||this.O()||(this.J?this.S=b:(this.pb(),
this.S=b,this.Qb()))}Cc(){return this.S}Gc(b){b?this.IsPlaying()?(this.xa=!0,this.S=this.Sa(),this.Y&&(this.S%=this.ga()),this.s.stop(0)):this.xa=!1:this.xa&&(V(this),this.s=this.V().createBufferSource(),this.s.buffer=this.P.ja,this.s.connect(this.G),this.rb=this.s,this.s.onended=this.ic,this.s.loop=this.Y,T(this,this.Qa),this.Ka(),this.s.start(0,this.S),this.mc=U(this),this.kc=this.S,this.xa=!1)}Nc(b){super.Nc(b);this.S=b.resumePosition}};"use strict";function W(b){return b.g.createGain()}
function X(b,a,c,d,e){a.cancelScheduledValues(0);if(0===e)a.value=c;else switch(b=b.g.currentTime,e+=b,d){case 0:a.setValueAtTime(c,e);break;case 1:a.setValueAtTime(a.value,b);a.linearRampToValueAtTime(c,e);break;case 2:a.setValueAtTime(a.value,b),a.exponentialRampToValueAtTime(c,e)}}class Y{constructor(b){this.v=b;this.g=b.V();this.ce=-1;this.T=this.rd="";this.o=null}l(){this.g=null}N(){}U(){}lb(){return{type:this.T,tag:this.rd,params:this.o}}}
self.ze=class extends Y{constructor(b,a,c,d,e,f,g){super(b);this.T="filter";this.o=[a,c,d,e,f,g];this.A=W(this);this.j=W(this);this.j.gain.value=g;this.h=W(this);this.h.gain.value=1-g;this.D=this.g.createBiquadFilter();this.D.type=a;this.D.frequency.value=c;this.D.detune.value=d;this.D.Q.value=e;this.D.gain.vlaue=f;this.A.connect(this.D);this.A.connect(this.h);this.D.connect(this.j)}l(){this.A.disconnect();this.D.disconnect();this.j.disconnect();this.h.disconnect();super.l()}U(b){this.j.disconnect();
this.j.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.A}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.o[5]=a;X(this,this.j.gain,a,c,d);X(this,this.h.gain,1-a,c,d);break;case 1:this.o[1]=a;X(this,this.D.frequency,a,c,d);break;case 2:this.o[2]=a;X(this,this.D.detune,a,c,d);break;case 3:this.o[3]=a;X(this,this.D.Q,a,c,d);break;case 4:this.o[4]=a,X(this,this.D.gain,a,c,d)}}};
self.xe=class extends Y{constructor(b,a,c,d){super(b);this.T="delay";this.o=[a,c,d];this.A=W(this);this.j=W(this);this.j.gain.value=d;this.h=W(this);this.h.gain.value=1-d;this.Db=W(this);this.X=this.g.createDelay(a);this.X.delayTime.value=a;this.vb=W(this);this.vb.gain.value=c;this.A.connect(this.Db);this.A.connect(this.h);this.Db.connect(this.j);this.Db.connect(this.X);this.X.connect(this.vb);this.vb.connect(this.Db)}l(){this.A.disconnect();this.j.disconnect();this.h.disconnect();this.Db.disconnect();
this.X.disconnect();this.vb.disconnect();super.l()}U(b){this.j.disconnect();this.j.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.A}Z(b,a,c,d){const e=self.jb.Dd;switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.o[2]=a;X(this,this.j.gain,a,c,d);X(this,this.h.gain,1-a,c,d);break;case 4:this.o[1]=e(a);X(this,this.vb.gain,e(a),c,d);break;case 5:this.o[0]=a,X(this,this.X.delayTime,a,c,d)}}};
self.we=class extends Y{constructor(b,a,c,d){super(b);this.T="convolution";this.o=[c,d];this.Ud=this.Td="";this.A=W(this);this.j=W(this);this.j.gain.value=d;this.h=W(this);this.h.gain.value=1-d;this.ub=this.g.createConvolver();this.ub.normalize=c;this.ub.buffer=a;this.A.connect(this.ub);this.A.connect(this.h);this.ub.connect(this.j)}l(){this.A.disconnect();this.ub.disconnect();this.j.disconnect();this.h.disconnect();super.l()}U(b){this.j.disconnect();this.j.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.A}Z(b,
a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0),this.o[1]=a,X(this,this.j.gain,a,c,d),X(this,this.h.gain,1-a,c,d)}}lb(){const b=super.lb();b.bufferOriginalUrl=this.Td;b.bufferUrl="";b.bufferType=this.Ud;return b}};
self.Ae=class extends Y{constructor(b,a,c,d,e,f){super(b);this.T="flanger";this.o=[a,c,d,e,f];this.A=W(this);this.h=W(this);this.h.gain.value=1-f/2;this.j=W(this);this.j.gain.value=f/2;this.wb=W(this);this.wb.gain.value=e;this.X=this.g.createDelay(a+c);this.X.delayTime.value=a;this.C=this.g.createOscillator();this.C.frequency.value=d;this.K=W(this);this.K.gain.value=c;this.A.connect(this.X);this.A.connect(this.h);this.X.connect(this.j);this.X.connect(this.wb);this.wb.connect(this.X);this.C.connect(this.K);
this.K.connect(this.X.delayTime);this.C.start(0)}l(){this.C.stop(0);this.A.disconnect();this.X.disconnect();this.C.disconnect();this.K.disconnect();this.h.disconnect();this.j.disconnect();this.wb.disconnect();super.l()}U(b){this.j.disconnect();this.j.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.A}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.o[4]=a;X(this,this.j.gain,a/2,c,d);X(this,this.h.gain,1-a/2,c,d);break;case 6:this.o[1]=a/1E3;X(this,this.K.gain,a/1E3,
c,d);break;case 7:this.o[2]=a;X(this,this.C.frequency,a,c,d);break;case 8:this.o[3]=a/100,X(this,this.wb.gain,a/100,c,d)}}};
self.Ce=class extends Y{constructor(b,a,c,d,e,f,g){super(b);this.T="phaser";this.o=[a,c,d,e,f,g];this.A=W(this);this.h=W(this);this.h.gain.value=1-g/2;this.j=W(this);this.j.gain.value=g/2;this.D=this.g.createBiquadFilter();this.D.type="allpass";this.D.frequency.value=a;this.D.detune.value=c;this.D.Q.value=d;this.C=this.g.createOscillator();this.C.frequency.value=f;this.K=W(this);this.K.gain.value=e;this.A.connect(this.D);this.A.connect(this.h);this.D.connect(this.j);this.C.connect(this.K);this.K.connect(this.D.frequency);
this.C.start(0)}l(){this.C.stop(0);this.A.disconnect();this.D.disconnect();this.C.disconnect();this.K.disconnect();this.h.disconnect();this.j.disconnect();super.l()}U(b){this.j.disconnect();this.j.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.A}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.o[5]=a;X(this,this.j.gain,a/2,c,d);X(this,this.h.gain,1-a/2,c,d);break;case 1:this.o[0]=a;X(this,this.D.frequency,a,c,d);break;case 2:this.o[1]=a;X(this,this.D.detune,a,c,d);
break;case 3:this.o[2]=a;X(this,this.D.Q,a,c,d);break;case 6:this.o[3]=a;X(this,this.K.gain,a,c,d);break;case 7:this.o[4]=a,X(this,this.C.frequency,a,c,d)}}};self.Be=class extends Y{constructor(b,a){super(b);this.T="gain";this.o=[a];this.m=W(this);this.m.gain.value=a}l(){this.m.disconnect();super.l()}U(b){this.m.disconnect();this.m.connect(b)}N(){return this.m}Z(b,a,c,d){const e=self.jb.Dd;switch(b){case 4:this.o[0]=e(a),X(this,this.m.gain,e(a),c,d)}}};
self.Ee=class extends Y{constructor(b,a){super(b);this.T="stereopan";this.o=[a];this.m=this.g.createStereoPanner();this.m.pan.value=a}l(){this.m.disconnect();super.l()}U(b){this.m.disconnect();this.m.connect(b)}N(){return this.m}Z(b,a,c,d){a=Math.min(Math.max(a/100,-1),1);switch(b){case 9:this.o[0]=a,X(this,this.m.pan,a,c,d)}}};
self.Fe=class extends Y{constructor(b,a,c){super(b);this.T="tremolo";this.o=[a,c];this.m=W(this);this.m.gain.value=1-c/2;this.C=this.g.createOscillator();this.C.frequency.value=a;this.K=W(this);this.K.gain.value=c/2;this.C.connect(this.K);this.K.connect(this.m.gain);this.C.start(0)}l(){this.C.stop(0);this.C.disconnect();this.K.disconnect();this.m.disconnect();super.l()}U(b){this.m.disconnect();this.m.connect(b)}N(){return this.m}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.o[1]=
a;X(this,this.m.gain,1-a/2,c,d);X(this,this.K.gain,a/2,c,d);break;case 7:this.o[0]=a,X(this,this.C.frequency,a,c,d)}}};
self.De=class extends Y{constructor(b,a,c){super(b);this.T="ringmod";this.o=[a,c];this.A=W(this);this.j=W(this);this.j.gain.value=c;this.h=W(this);this.h.gain.value=1-c;this.Jb=W(this);this.Jb.gain.value=0;this.C=this.g.createOscillator();this.C.frequency.value=a;this.C.connect(this.Jb.gain);this.C.start(0);this.A.connect(this.Jb);this.A.connect(this.h);this.Jb.connect(this.j)}l(){this.C.stop(0);this.C.disconnect();this.Jb.disconnect();this.A.disconnect();this.j.disconnect();this.h.disconnect();super.l()}U(b){this.j.disconnect();
this.j.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.A}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.o[1]=a;X(this,this.j.gain,a,c,d);X(this,this.h.gain,1-a,c,d);break;case 7:this.o[0]=a,X(this,this.C.frequency,a,c,d)}}};
self.ye=class extends Y{constructor(b,a,c,d,e,f){super(b);this.T="distortion";this.o=[a,c,d,e,f];this.A=W(this);this.oc=W(this);this.nc=W(this);b=d;.01>b&&(b=.01);this.oc.gain.value=b;this.nc.gain.value=Math.pow(1/b,.6)*e;this.j=W(this);this.j.gain.value=f;this.h=W(this);this.h.gain.value=1-f;this.sc=this.g.createWaveShaper();this.Vc=new Float32Array(65536);for(e=0;32768>e;++e)f=e/32768,b=1.05*c*a-a,d=0>f?-f:f,d<a?b=d:(d=1-Math.exp(-(1/b)*(d-a)),b=a+b*d),f=b*(0>f?-1:1),this.Vc[32768+e]=f,this.Vc[32768-
e-1]=-f;this.sc.curve=this.Vc;this.A.connect(this.oc);this.A.connect(this.h);this.oc.connect(this.sc);this.sc.connect(this.nc);this.nc.connect(this.j)}l(){this.A.disconnect();this.oc.disconnect();this.sc.disconnect();this.nc.disconnect();this.j.disconnect();this.h.disconnect();super.l()}U(b){this.j.disconnect();this.j.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.A}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0),this.o[4]=a,X(this,this.j.gain,a,c,d),X(this,this.h.gain,
1-a,c,d)}}};self.ve=class extends Y{constructor(b,a,c,d,e,f){super(b);this.T="compressor";this.o=[a,c,d,e,f];this.m=this.g.createDynamicsCompressor();this.m.threshold.value=a;this.m.knee.value=c;this.m.ratio.value=d;this.m.attack.value=e;this.m.release.value=f}l(){this.m.disconnect();super.l()}U(b){this.m.disconnect();this.m.connect(b)}N(){return this.m}Z(){}};
self.ue=class extends Y{constructor(b,a,c){super(b);this.T="analyser";this.o=[a,c];this.m=this.g.createAnalyser();this.m.fftSize=a;this.m.smoothingTimeConstant=c;this.$d=new Float32Array(this.m.frequencyBinCount);this.ne=new Uint8Array(a);this.le=this.cb=0;b=this.v;b.Ua.add(this);S(b)}l(){this.v.Ua.delete(this);this.m.disconnect();super.l()}Ia(){this.m.getFloatFrequencyData(this.$d);this.m.getByteTimeDomainData(this.ne);const b=this.m.fftSize;let a=this.cb=0;for(var c=0;c<b;++c){let d=(this.ne[c]-
128)/128;0>d&&(d=-d);this.cb<d&&(this.cb=d);a+=d*d}c=self.jb.Qe;this.cb=c(this.cb);this.le=c(Math.sqrt(a/b))}U(b){this.m.disconnect();this.m.connect(b)}N(){return this.m}Z(){}};"use strict";function Z(b){b.stopPropagation()}
self.ra.Ra(class extends self.Nb{constructor(b){super(b,"button")}wc(b,a){const c=document.createElement("input");var d=c;a.isCheckbox?(c.type="checkbox",d=document.createElement("label"),d.appendChild(c),d.appendChild(document.createTextNode("")),d.style.fontFamily="sans-serif",d.style.userSelect="none",d.style.webkitUserSelect="none",d.style.display="inline-block",d.style.color="black"):c.type="button";d.style.position="absolute";d.addEventListener("pointerdown",Z);d.addEventListener("pointermove",
Z);d.addEventListener("pointerrawupdate",Z);d.addEventListener("pointerup",Z);d.addEventListener("mousedown",Z);d.addEventListener("mouseup",Z);d.addEventListener("keydown",Z);d.addEventListener("keyup",Z);d.addEventListener("contextmenu",e=>e.preventDefault());c.addEventListener("click",()=>{var e={isChecked:c.checked};e.elementId=b;n(this,"click",e)});a.id&&(c.id=a.id);a.className&&(c.className=a.className);this.Sb(d,a);return d}Kc(b){return"input"===b.tagName.toLowerCase()?b:b.firstChild}Sb(b,
a){const c="input"===b.tagName.toLowerCase()?b:b.firstChild;c.checked=a.isChecked;c.disabled=!a.isEnabled;b.title=a.title;b===c?c.value=a.text:b.lastChild.textContent=a.text}});
