// NOTE: this file is auto-generated by Construct
declare namespace InstanceType {
	class ajax extends IInstance {
	}
	class equipmentArray extends IArrayInstance {
	}
	class keyboard extends IInstance {
	}
	class advancedRandom extends IInstance {
	}
	class mouse extends IInstance {
	}
	class browser extends IInstance {
	}
	class abilitiesArray extends IArrayInstance {
	}
	class video extends IWorldInstance {
	}
	class abilityOptionsArray extends IArrayInstance {
	}
	class npcDialogArray extends IArrayInstance {
	}
	class audio extends IInstance {
	}
	class gearQueueArray extends IArrayInstance {
	}
	class soundEffectVariants extends IDictionaryInstance {
	}
	class layoutProperties extends IArrayInstance {
	}
	class mods extends IDictionaryInstance {
	}
	class healthCover extends ISpriteInstance {
	}
	class manaOrb extends ITiledBackgroundInstance {
	}
	class healthOrb extends ITiledBackgroundInstance {
	}
	class __healthStatueBehaviors<InstType> {
		Anchor: IAnchorBehaviorInstance<InstType>;
		DragDrop: IDragDropBehaviorInstance<InstType>;
		Tween: ITweenBehaviorInstance<InstType>;
	}
	class healthStatue extends ISpriteInstance {
		instVars: {
			originalX: number,
			originalY: number
		};
		behaviors: __healthStatueBehaviors<this>;
	}
	class __manaStatueBehaviors<InstType> {
		Anchor: IAnchorBehaviorInstance<InstType>;
		DragDrop: IDragDropBehaviorInstance<InstType>;
		Tween: ITweenBehaviorInstance<InstType>;
	}
	class manaStatue extends ISpriteInstance {
		instVars: {
			originalX: number,
			originalY: number
		};
		behaviors: __manaStatueBehaviors<this>;
	}
	class manaCover extends ISpriteInstance {
	}
	class orbCoverFront extends ISpriteInstance {
	}
	class orbCoverBack extends ISpriteInstance {
	}
	class tooltipName extends ITextInstance {
	}
	class tooltipClass extends ITextInstance {
	}
	class tooltipDescription extends ITextInstance {
	}
	class tooltipLevel extends ITextInstance {
	}
	class tooltipLore extends ITextInstance {
	}
	class __tooltipBehaviors<InstType> {
		Tween: ITweenBehaviorInstance<InstType>;
	}
	class tooltip extends IWorldInstance {
		behaviors: __tooltipBehaviors<this>;
	}
	class tooltipValue extends ITextInstance {
	}
	class __logoBehaviors<InstType> {
		Anchor: IAnchorBehaviorInstance<InstType>;
	}
	class logo extends ITiledBackgroundInstance {
		behaviors: __logoBehaviors<this>;
	}
	class __versionTextBehaviors<InstType> {
		Anchor: IAnchorBehaviorInstance<InstType>;
	}
	class versionText extends ITextInstance {
		behaviors: __versionTextBehaviors<this>;
	}
	class loadingText extends ITextInstance {
	}
	class loadingTextBackground extends ITiledBackgroundInstance {
	}
	class loadingScreen extends ITiledBackgroundInstance {
	}
	class laserwolveGamesLogo extends ISpriteInstance {
	}
	class chestPlaceholder extends ISpriteInstance {
	}
	class feetPlaceholder extends ISpriteInstance {
	}
	class handsPlaceholder extends ISpriteInstance {
	}
	class headPlaceholder extends ISpriteInstance {
	}
	class legsPlaceholder extends ISpriteInstance {
	}
	class mainHandPlaceholder extends ISpriteInstance {
	}
	class neckPlaceholder extends ISpriteInstance {
	}
	class offHandPlaceholder extends ISpriteInstance {
	}
	class ringPlaceholder extends ISpriteInstance {
	}
	class __equippedMenuStatueBehaviors<InstType> {
		Anchor: IAnchorBehaviorInstance<InstType>;
		DragDrop: IDragDropBehaviorInstance<InstType>;
		Tween: ITweenBehaviorInstance<InstType>;
	}
	class equippedMenuStatue extends ISpriteInstance {
		instVars: {
			originalX: number,
			originalY: number
		};
		behaviors: __equippedMenuStatueBehaviors<this>;
	}
	class __inventoryMenuStatueBehaviors<InstType> {
		Anchor: IAnchorBehaviorInstance<InstType>;
		DragDrop: IDragDropBehaviorInstance<InstType>;
		Tween: ITweenBehaviorInstance<InstType>;
	}
	class inventoryMenuStatue extends ISpriteInstance {
		instVars: {
			originalX: number,
			originalY: number
		};
		behaviors: __inventoryMenuStatueBehaviors<this>;
	}
	class __abilityBarStatueBehaviors<InstType> {
		Anchor: IAnchorBehaviorInstance<InstType>;
		DragDrop: IDragDropBehaviorInstance<InstType>;
		Tween: ITweenBehaviorInstance<InstType>;
	}
	class abilityBarStatue extends ISpriteInstance {
		instVars: {
			originalX: number,
			originalY: number
		};
		behaviors: __abilityBarStatueBehaviors<this>;
	}
	class __abilitySelectorStatueBehaviors<InstType> {
		Anchor: IAnchorBehaviorInstance<InstType>;
		DragDrop: IDragDropBehaviorInstance<InstType>;
		Tween: ITweenBehaviorInstance<InstType>;
	}
	class abilitySelectorStatue extends ISpriteInstance {
		instVars: {
			originalX: number,
			originalY: number
		};
		behaviors: __abilitySelectorStatueBehaviors<this>;
	}
	class __characterMenuStatueBehaviors<InstType> {
		Anchor: IAnchorBehaviorInstance<InstType>;
		DragDrop: IDragDropBehaviorInstance<InstType>;
		Tween: ITweenBehaviorInstance<InstType>;
	}
	class characterMenuStatue extends ISpriteInstance {
		instVars: {
			originalX: number,
			originalY: number
		};
		behaviors: __characterMenuStatueBehaviors<this>;
	}
	class __settingsMenuStatueBehaviors<InstType> {
		Anchor: IAnchorBehaviorInstance<InstType>;
		DragDrop: IDragDropBehaviorInstance<InstType>;
		Tween: ITweenBehaviorInstance<InstType>;
	}
	class settingsMenuStatue extends ISpriteInstance {
		instVars: {
			originalX: number,
			originalY: number
		};
		behaviors: __settingsMenuStatueBehaviors<this>;
	}
	class __merchantMenuStatueBehaviors<InstType> {
		Anchor: IAnchorBehaviorInstance<InstType>;
		DragDrop: IDragDropBehaviorInstance<InstType>;
		Tween: ITweenBehaviorInstance<InstType>;
	}
	class merchantMenuStatue extends ISpriteInstance {
		instVars: {
			originalX: number,
			originalY: number,
			merchantStore: string
		};
		behaviors: __merchantMenuStatueBehaviors<this>;
	}
	class __dialogStatueBehaviors<InstType> {
		Anchor: IAnchorBehaviorInstance<InstType>;
		DragDrop: IDragDropBehaviorInstance<InstType>;
		Tween: ITweenBehaviorInstance<InstType>;
	}
	class dialogStatue extends ISpriteInstance {
		instVars: {
			originalX: number,
			originalY: number
		};
		behaviors: __dialogStatueBehaviors<this>;
	}
	class settingsText extends ITextInstance {
	}
	class tutorialText extends ITextInstance {
	}
	class autoEquip extends ISpriteInstance {
	}
	class abilityKeybinder extends ITextInstance {
		instVars: {
			keycode: number,
			abilityNumber: number
		};
	}
	class slot extends IWorldInstance {
		instVars: {
			identifier: number,
			type: string
		};
	}
	class characterMenu extends IWorldInstance {
	}
	class settingsMenu extends IWorldInstance {
	}
	class tutorial extends IWorldInstance {
	}
	class __playBehaviors<InstType> {
		Anchor: IAnchorBehaviorInstance<InstType>;
	}
	class play extends ITextInstance {
		instVars: {
			originalX: number,
			originalY: number,
			originalFaceSize: number
		};
		behaviors: __playBehaviors<this>;
	}
	class back extends ITextInstance {
		instVars: {
			originalX: number,
			originalY: number,
			originalFaceSize: number
		};
	}
	class man_ability extends ISpriteInstance {
	}
	class abilitySlot extends IWorldInstance {
		instVars: {
			unlockLevel: number,
			abilityNumber: number
		};
	}
	class abilityKey extends ITextInstance {
	}
	class __comparisonTooltipBehaviors<InstType> {
		Tween: ITweenBehaviorInstance<InstType>;
	}
	class comparisonTooltip extends IWorldInstance {
		behaviors: __comparisonTooltipBehaviors<this>;
	}
	class comparisonTooltipClass extends ITextInstance {
	}
	class comparisonTooltipDescription extends ITextInstance {
	}
	class comparisonTooltipLevel extends ITextInstance {
	}
	class comparisonTooltipLore extends ITextInstance {
	}
	class comparisonTooltipName extends ITextInstance {
	}
	class currentlyEquipped extends ITextInstance {
	}
	class comparisonTooltipValue extends ITextInstance {
	}
	class enemyAttributes extends ITextInstance {
	}
	class enemyHealthBar extends ITiledBackgroundInstance {
	}
	class __enemyHealthFrameBehaviors<InstType> {
		Anchor: IAnchorBehaviorInstance<InstType>;
		Tween: ITweenBehaviorInstance<InstType>;
	}
	class enemyHealthFrame extends IWorldInstance {
		behaviors: __enemyHealthFrameBehaviors<this>;
	}
	class enemyName extends ITextInstance {
	}
	class dialog extends IWorldInstance {
	}
	class dialogNpcName extends ITextInstance {
	}
	class dialogText extends ITextInstance {
	}
	class characterName extends ITextInstance {
	}
	class class extends ITextInstance {
	}
	class characterMenuText extends ITextInstance {
	}
	class maxHealth extends ITextInstance {
	}
	class healthRegen extends ITextInstance {
	}
	class actionSpeed extends ITextInstance {
	}
	class attackRange extends ITextInstance {
	}
	class pickupRange extends ITextInstance {
	}
	class movementSpeed extends ITextInstance {
	}
	class flinchResistance extends ITextInstance {
	}
	class armor extends ITextInstance {
	}
	class maxMana extends ITextInstance {
	}
	class manaRegen extends ITextInstance {
	}
	class physicalResistance extends ITextInstance {
	}
	class coldResistance extends ITextInstance {
	}
	class fireResistance extends ITextInstance {
	}
	class lightningResistance extends ITextInstance {
	}
	class corruptResistance extends ITextInstance {
	}
	class arcaneResistance extends ITextInstance {
	}
	class slashDamage extends ITextInstance {
	}
	class smashDamage extends ITextInstance {
	}
	class stabDamage extends ITextInstance {
	}
	class coldDamage extends ITextInstance {
	}
	class fireDamage extends ITextInstance {
	}
	class lightningDamage extends ITextInstance {
	}
	class arcaneDamage extends ITextInstance {
	}
	class holyDamage extends ITextInstance {
	}
	class __launcherMessageBehaviors<InstType> {
		Tween: ITweenBehaviorInstance<InstType>;
		Anchor: IAnchorBehaviorInstance<InstType>;
	}
	class launcherMessage extends ITextInstance {
		behaviors: __launcherMessageBehaviors<this>;
	}
	class __loadingBarFrameBehaviors<InstType> {
		Anchor: IAnchorBehaviorInstance<InstType>;
	}
	class loadingBarFrame extends IWorldInstance {
		behaviors: __loadingBarFrameBehaviors<this>;
	}
	class loadingBar extends ITiledBackgroundInstance {
	}
	class loadingBarText extends ITextInstance {
	}
	class splashScreen extends ITiledBackgroundInstance {
	}
	class __copyrightBehaviors<InstType> {
		Anchor: IAnchorBehaviorInstance<InstType>;
	}
	class copyright extends ITextInstance {
		behaviors: __copyrightBehaviors<this>;
	}
	class coinsIcon extends ISpriteInstance {
	}
	class coinsTotal extends ITextInstance {
	}
	class __faderBehaviors<InstType> {
		Tween: ITweenBehaviorInstance<InstType>;
	}
	class fader extends ITiledBackgroundInstance {
		behaviors: __faderBehaviors<this>;
	}
	class man extends ISpriteInstance {
		instVars: {
			yValue: number,
			doNotCreateShadow: boolean
		};
	}
	class __goblinArcherBehaviors<InstType> {
		Tween: ITweenBehaviorInstance<InstType>;
		Persist: IBehaviorInstance<InstType>;
	}
	class goblinArcher extends ISpriteInstance {
		instVars: {
			yValue: number,
			doNotCreateShadow: boolean
		};
		behaviors: __goblinArcherBehaviors<this>;
	}
	class __goblinUnderlingBehaviors<InstType> {
		Tween: ITweenBehaviorInstance<InstType>;
		Persist: IBehaviorInstance<InstType>;
	}
	class goblinUnderling extends ISpriteInstance {
		instVars: {
			yValue: number,
			doNotCreateShadow: boolean
		};
		behaviors: __goblinUnderlingBehaviors<this>;
	}
	class __goblinWarlockBehaviors<InstType> {
		Tween: ITweenBehaviorInstance<InstType>;
		Persist: IBehaviorInstance<InstType>;
	}
	class goblinWarlock extends ISpriteInstance {
		instVars: {
			yValue: number,
			doNotCreateShadow: boolean
		};
		behaviors: __goblinWarlockBehaviors<this>;
	}
	class __guideBehaviors<InstType> {
		Persist: IBehaviorInstance<InstType>;
	}
	class guide extends ISpriteInstance {
		instVars: {
			yValue: number,
			doNotCreateShadow: boolean
		};
		behaviors: __guideBehaviors<this>;
	}
	class __merchantBehaviors<InstType> {
		Persist: IBehaviorInstance<InstType>;
	}
	class merchant extends ISpriteInstance {
		instVars: {
			yValue: number,
			doNotCreateShadow: boolean
		};
		behaviors: __merchantBehaviors<this>;
	}
	class man_legsDefault_gear extends ISpriteInstance {
		instVars: {
			type: string,
			doNotCreateShadow: boolean
		};
	}
	class man_headDefault_gear extends ISpriteInstance {
		instVars: {
			type: string,
			doNotCreateShadow: boolean
		};
	}
	class man_maraudersBracers_gear extends ISpriteInstance {
		instVars: {
			type: string,
			doNotCreateShadow: boolean
		};
	}
	class man_maraudersStraps_gear extends ISpriteInstance {
		instVars: {
			type: string,
			doNotCreateShadow: boolean
		};
	}
	class man_simpleGloves_gear extends ISpriteInstance {
		instVars: {
			type: string,
			doNotCreateShadow: boolean
		};
	}
	class man_leggings_gear extends ISpriteInstance {
		instVars: {
			type: string,
			doNotCreateShadow: boolean
		};
	}
	class man_simpleShirt_gear extends ISpriteInstance {
		instVars: {
			type: string,
			doNotCreateShadow: boolean
		};
	}
	class man_simpleShield_gear extends ISpriteInstance {
		instVars: {
			type: string,
			doNotCreateShadow: boolean
		};
	}
	class man_simpleSword_gear extends ISpriteInstance {
		instVars: {
			type: string,
			doNotCreateShadow: boolean
		};
	}
	class man_crudeHelmet_gear extends ISpriteInstance {
		instVars: {
			type: string,
			doNotCreateShadow: boolean
		};
	}
	class man_ornateShield_gear extends ISpriteInstance {
		instVars: {
			type: string,
			doNotCreateShadow: boolean
		};
	}
	class man_simpleHelmet_gear extends ISpriteInstance {
		instVars: {
			type: string,
			doNotCreateShadow: boolean
		};
	}
	class man_simpleMace_gear extends ISpriteInstance {
		instVars: {
			type: string,
			doNotCreateShadow: boolean
		};
	}
	class man_simplePants_gear extends ISpriteInstance {
		instVars: {
			type: string,
			doNotCreateShadow: boolean
		};
	}
	class man_strappedBoots_gear extends ISpriteInstance {
		instVars: {
			type: string,
			doNotCreateShadow: boolean
		};
	}
	class __maraudersBracers_lootBehaviors<InstType> {
		Tween: ITweenBehaviorInstance<InstType>;
		Persist: IBehaviorInstance<InstType>;
	}
	class maraudersBracers_loot extends ISpriteInstance {
		instVars: {
			identifier: number,
			pickupRangeBonus: number,
			destinationX: number,
			destinationY: number,
			level: number,
			value: number,
			simpleName: string,
			fullName: string,
			type: string,
			lore: string,
			mods: string,
			classRestrictions: string,
			sound: string
		};
		behaviors: __maraudersBracers_lootBehaviors<this>;
	}
	class __crudeHelmet_lootBehaviors<InstType> {
		Tween: ITweenBehaviorInstance<InstType>;
		Persist: IBehaviorInstance<InstType>;
	}
	class crudeHelmet_loot extends ISpriteInstance {
		instVars: {
			identifier: number,
			pickupRangeBonus: number,
			destinationX: number,
			destinationY: number,
			level: number,
			value: number,
			simpleName: string,
			fullName: string,
			type: string,
			lore: string,
			mods: string,
			classRestrictions: string,
			sound: string
		};
		behaviors: __crudeHelmet_lootBehaviors<this>;
	}
	class __ornateShield_lootBehaviors<InstType> {
		Tween: ITweenBehaviorInstance<InstType>;
		Persist: IBehaviorInstance<InstType>;
	}
	class ornateShield_loot extends ISpriteInstance {
		instVars: {
			identifier: number,
			pickupRangeBonus: number,
			destinationX: number,
			destinationY: number,
			level: number,
			value: number,
			simpleName: string,
			fullName: string,
			type: string,
			lore: string,
			mods: string,
			classRestrictions: string,
			sound: string
		};
		behaviors: __ornateShield_lootBehaviors<this>;
	}
	class __simpleHelmet_lootBehaviors<InstType> {
		Tween: ITweenBehaviorInstance<InstType>;
		Persist: IBehaviorInstance<InstType>;
	}
	class simpleHelmet_loot extends ISpriteInstance {
		instVars: {
			identifier: number,
			pickupRangeBonus: number,
			destinationX: number,
			destinationY: number,
			level: number,
			value: number,
			simpleName: string,
			fullName: string,
			type: string,
			lore: string,
			mods: string,
			classRestrictions: string,
			sound: string
		};
		behaviors: __simpleHelmet_lootBehaviors<this>;
	}
	class __simpleMace_lootBehaviors<InstType> {
		Tween: ITweenBehaviorInstance<InstType>;
		Persist: IBehaviorInstance<InstType>;
	}
	class simpleMace_loot extends ISpriteInstance {
		instVars: {
			identifier: number,
			pickupRangeBonus: number,
			destinationX: number,
			destinationY: number,
			level: number,
			value: number,
			simpleName: string,
			fullName: string,
			type: string,
			lore: string,
			mods: string,
			classRestrictions: string,
			sound: string
		};
		behaviors: __simpleMace_lootBehaviors<this>;
	}
	class __simplePants_lootBehaviors<InstType> {
		Tween: ITweenBehaviorInstance<InstType>;
		Persist: IBehaviorInstance<InstType>;
	}
	class simplePants_loot extends ISpriteInstance {
		instVars: {
			identifier: number,
			pickupRangeBonus: number,
			destinationX: number,
			destinationY: number,
			level: number,
			value: number,
			simpleName: string,
			fullName: string,
			type: string,
			lore: string,
			mods: string,
			classRestrictions: string,
			sound: string
		};
		behaviors: __simplePants_lootBehaviors<this>;
	}
	class __strappedBoots_lootBehaviors<InstType> {
		Tween: ITweenBehaviorInstance<InstType>;
		Persist: IBehaviorInstance<InstType>;
	}
	class strappedBoots_loot extends ISpriteInstance {
		instVars: {
			identifier: number,
			pickupRangeBonus: number,
			destinationX: number,
			destinationY: number,
			level: number,
			value: number,
			simpleName: string,
			fullName: string,
			type: string,
			lore: string,
			mods: string,
			classRestrictions: string,
			sound: string
		};
		behaviors: __strappedBoots_lootBehaviors<this>;
	}
	class __maraudersStraps_lootBehaviors<InstType> {
		Tween: ITweenBehaviorInstance<InstType>;
		Persist: IBehaviorInstance<InstType>;
	}
	class maraudersStraps_loot extends ISpriteInstance {
		instVars: {
			identifier: number,
			pickupRangeBonus: number,
			destinationX: number,
			destinationY: number,
			level: number,
			value: number,
			simpleName: string,
			fullName: string,
			type: string,
			lore: string,
			mods: string,
			classRestrictions: string,
			sound: string
		};
		behaviors: __maraudersStraps_lootBehaviors<this>;
	}
	class __simpleGloves_lootBehaviors<InstType> {
		Tween: ITweenBehaviorInstance<InstType>;
		Persist: IBehaviorInstance<InstType>;
	}
	class simpleGloves_loot extends ISpriteInstance {
		instVars: {
			identifier: number,
			pickupRangeBonus: number,
			destinationX: number,
			destinationY: number,
			level: number,
			value: number,
			simpleName: string,
			fullName: string,
			type: string,
			lore: string,
			mods: string,
			classRestrictions: string,
			sound: string
		};
		behaviors: __simpleGloves_lootBehaviors<this>;
	}
	class __leggings_lootBehaviors<InstType> {
		Tween: ITweenBehaviorInstance<InstType>;
		Persist: IBehaviorInstance<InstType>;
	}
	class leggings_loot extends ISpriteInstance {
		instVars: {
			identifier: number,
			pickupRangeBonus: number,
			destinationX: number,
			destinationY: number,
			level: number,
			value: number,
			simpleName: string,
			fullName: string,
			type: string,
			lore: string,
			mods: string,
			classRestrictions: string,
			sound: string
		};
		behaviors: __leggings_lootBehaviors<this>;
	}
	class __simpleShirt_lootBehaviors<InstType> {
		Tween: ITweenBehaviorInstance<InstType>;
		Persist: IBehaviorInstance<InstType>;
	}
	class simpleShirt_loot extends ISpriteInstance {
		instVars: {
			identifier: number,
			pickupRangeBonus: number,
			destinationX: number,
			destinationY: number,
			level: number,
			value: number,
			simpleName: string,
			fullName: string,
			type: string,
			lore: string,
			mods: string,
			classRestrictions: string,
			sound: string
		};
		behaviors: __simpleShirt_lootBehaviors<this>;
	}
	class __simpleShield_lootBehaviors<InstType> {
		Tween: ITweenBehaviorInstance<InstType>;
		Persist: IBehaviorInstance<InstType>;
	}
	class simpleShield_loot extends ISpriteInstance {
		instVars: {
			identifier: number,
			pickupRangeBonus: number,
			destinationX: number,
			destinationY: number,
			level: number,
			value: number,
			simpleName: string,
			fullName: string,
			type: string,
			lore: string,
			mods: string,
			classRestrictions: string,
			sound: string
		};
		behaviors: __simpleShield_lootBehaviors<this>;
	}
	class __simpleSword_lootBehaviors<InstType> {
		Tween: ITweenBehaviorInstance<InstType>;
		Persist: IBehaviorInstance<InstType>;
	}
	class simpleSword_loot extends ISpriteInstance {
		instVars: {
			identifier: number,
			pickupRangeBonus: number,
			destinationX: number,
			destinationY: number,
			level: number,
			value: number,
			simpleName: string,
			fullName: string,
			type: string,
			lore: string,
			mods: string,
			classRestrictions: string,
			sound: string
		};
		behaviors: __simpleSword_lootBehaviors<this>;
	}
	class __maraudersBracers_itemBehaviors<InstType> {
		DragDrop: IDragDropBehaviorInstance<InstType>;
		Tween: ITweenBehaviorInstance<InstType>;
	}
	class maraudersBracers_item extends ISpriteInstance {
		instVars: {
			identifier: number,
			level: number,
			value: number,
			simpleName: string,
			fullName: string,
			type: string,
			lore: string,
			mods: string,
			classRestrictions: string,
			sound: string
		};
		behaviors: __maraudersBracers_itemBehaviors<this>;
	}
	class __crudeHelmet_itemBehaviors<InstType> {
		DragDrop: IDragDropBehaviorInstance<InstType>;
		Tween: ITweenBehaviorInstance<InstType>;
	}
	class crudeHelmet_item extends ISpriteInstance {
		instVars: {
			identifier: number,
			level: number,
			value: number,
			simpleName: string,
			fullName: string,
			type: string,
			lore: string,
			mods: string,
			classRestrictions: string,
			sound: string
		};
		behaviors: __crudeHelmet_itemBehaviors<this>;
	}
	class __simpleHelmet_itemBehaviors<InstType> {
		DragDrop: IDragDropBehaviorInstance<InstType>;
		Tween: ITweenBehaviorInstance<InstType>;
	}
	class simpleHelmet_item extends ISpriteInstance {
		instVars: {
			identifier: number,
			level: number,
			value: number,
			simpleName: string,
			fullName: string,
			type: string,
			lore: string,
			mods: string,
			classRestrictions: string,
			sound: string
		};
		behaviors: __simpleHelmet_itemBehaviors<this>;
	}
	class __simpleMace_itemBehaviors<InstType> {
		DragDrop: IDragDropBehaviorInstance<InstType>;
		Tween: ITweenBehaviorInstance<InstType>;
	}
	class simpleMace_item extends ISpriteInstance {
		instVars: {
			identifier: number,
			level: number,
			value: number,
			simpleName: string,
			fullName: string,
			type: string,
			lore: string,
			mods: string,
			classRestrictions: string,
			sound: string
		};
		behaviors: __simpleMace_itemBehaviors<this>;
	}
	class __simplePants_itemBehaviors<InstType> {
		DragDrop: IDragDropBehaviorInstance<InstType>;
		Tween: ITweenBehaviorInstance<InstType>;
	}
	class simplePants_item extends ISpriteInstance {
		instVars: {
			identifier: number,
			level: number,
			value: number,
			simpleName: string,
			fullName: string,
			type: string,
			lore: string,
			mods: string,
			classRestrictions: string,
			sound: string
		};
		behaviors: __simplePants_itemBehaviors<this>;
	}
	class __simpleShield_itemBehaviors<InstType> {
		DragDrop: IDragDropBehaviorInstance<InstType>;
		Tween: ITweenBehaviorInstance<InstType>;
	}
	class simpleShield_item extends ISpriteInstance {
		instVars: {
			identifier: number,
			level: number,
			value: number,
			simpleName: string,
			fullName: string,
			type: string,
			lore: string,
			mods: string,
			classRestrictions: string,
			sound: string
		};
		behaviors: __simpleShield_itemBehaviors<this>;
	}
	class __strappedBoots_itemBehaviors<InstType> {
		DragDrop: IDragDropBehaviorInstance<InstType>;
		Tween: ITweenBehaviorInstance<InstType>;
	}
	class strappedBoots_item extends ISpriteInstance {
		instVars: {
			identifier: number,
			level: number,
			value: number,
			simpleName: string,
			fullName: string,
			type: string,
			lore: string,
			mods: string,
			classRestrictions: string,
			sound: string
		};
		behaviors: __strappedBoots_itemBehaviors<this>;
	}
	class __maraudersStraps_itemBehaviors<InstType> {
		DragDrop: IDragDropBehaviorInstance<InstType>;
		Tween: ITweenBehaviorInstance<InstType>;
	}
	class maraudersStraps_item extends ISpriteInstance {
		instVars: {
			identifier: number,
			level: number,
			value: number,
			simpleName: string,
			fullName: string,
			type: string,
			lore: string,
			mods: string,
			classRestrictions: string,
			sound: string
		};
		behaviors: __maraudersStraps_itemBehaviors<this>;
	}
	class __simpleGloves_itemBehaviors<InstType> {
		DragDrop: IDragDropBehaviorInstance<InstType>;
		Tween: ITweenBehaviorInstance<InstType>;
	}
	class simpleGloves_item extends ISpriteInstance {
		instVars: {
			identifier: number,
			level: number,
			value: number,
			simpleName: string,
			fullName: string,
			type: string,
			lore: string,
			mods: string,
			classRestrictions: string,
			sound: string
		};
		behaviors: __simpleGloves_itemBehaviors<this>;
	}
	class __leggings_itemBehaviors<InstType> {
		DragDrop: IDragDropBehaviorInstance<InstType>;
		Tween: ITweenBehaviorInstance<InstType>;
	}
	class leggings_item extends ISpriteInstance {
		instVars: {
			identifier: number,
			level: number,
			value: number,
			simpleName: string,
			fullName: string,
			type: string,
			lore: string,
			mods: string,
			classRestrictions: string,
			sound: string
		};
		behaviors: __leggings_itemBehaviors<this>;
	}
	class __simpleShirt_itemBehaviors<InstType> {
		DragDrop: IDragDropBehaviorInstance<InstType>;
		Tween: ITweenBehaviorInstance<InstType>;
	}
	class simpleShirt_item extends ISpriteInstance {
		instVars: {
			identifier: number,
			level: number,
			value: number,
			simpleName: string,
			fullName: string,
			type: string,
			lore: string,
			mods: string,
			classRestrictions: string,
			sound: string
		};
		behaviors: __simpleShirt_itemBehaviors<this>;
	}
	class __ornateShield_itemBehaviors<InstType> {
		DragDrop: IDragDropBehaviorInstance<InstType>;
		Tween: ITweenBehaviorInstance<InstType>;
	}
	class ornateShield_item extends ISpriteInstance {
		instVars: {
			identifier: number,
			level: number,
			value: number,
			simpleName: string,
			fullName: string,
			type: string,
			lore: string,
			mods: string,
			classRestrictions: string,
			sound: string
		};
		behaviors: __ornateShield_itemBehaviors<this>;
	}
	class __simpleSword_itemBehaviors<InstType> {
		DragDrop: IDragDropBehaviorInstance<InstType>;
		Tween: ITweenBehaviorInstance<InstType>;
	}
	class simpleSword_item extends ISpriteInstance {
		instVars: {
			identifier: number,
			level: number,
			value: number,
			simpleName: string,
			fullName: string,
			type: string,
			lore: string,
			mods: string,
			classRestrictions: string,
			sound: string
		};
		behaviors: __simpleSword_itemBehaviors<this>;
	}
	class __boundaryBehaviors<InstType> {
		Solid: ISolidBehaviorInstance<InstType>;
	}
	class boundary extends ISpriteInstance {
		behaviors: __boundaryBehaviors<this>;
	}
	class dirt extends ITiledBackgroundInstance {
	}
	class grass extends ITiledBackgroundInstance {
	}
	class nonCombatArea extends ISpriteInstance {
	}
	class __enemyBehaviors<InstType> {
		MoveTo: IMoveToBehaviorInstance<InstType>;
		Solid: ISolidBehaviorInstance<InstType>;
		knockback: IMoveToBehaviorInstance<InstType>;
		LineOfSight: ILOSBehaviorInstance<InstType>;
		Persist: IBehaviorInstance<InstType>;
	}
	class enemy extends ISpriteInstance {
		instVars: {
			simpleName: string,
			fullName: string,
			type: string,
			movementSpeed: number,
			degrees: number,
			attributes: string,
			experience: number,
			currentHealth: number,
			maxHealth: number,
			attackSpeed: number,
			slashDamage: number,
			smashDamage: number,
			stabDamage: number,
			coldDamage: number,
			fireDamage: number,
			lightningDamage: number,
			arcaneDamage: number,
			corruptDamage: number,
			attackRange: number,
			physicalResistance: number,
			coldResistance: number,
			fireResistance: number,
			lightningResistance: number,
			arcaneResistance: number,
			holyResistance: number,
			attacking: boolean,
			hit: boolean,
			rerouting: string
		};
		behaviors: __enemyBehaviors<this>;
	}
	class __playerBehaviors<InstType> {
		MoveTo: IMoveToBehaviorInstance<InstType>;
		BoundToLayout: IBehaviorInstance<InstType>;
		Solid: ISolidBehaviorInstance<InstType>;
		ScrollTo: IBehaviorInstance<InstType>;
		Custom: IBehaviorInstance<InstType>;
	}
	class player extends ISpriteInstance {
		instVars: {
			level: number,
			experience: number,
			coins: number,
			actionSpeed: number,
			movementSpeed: number,
			pickupRange: number,
			attackRange: number,
			currentHealth: number,
			maxHealth: number,
			healthRegen: number,
			currentMana: number,
			maxMana: number,
			manaRegen: number,
			armor: number,
			slashDamage: number,
			smashDamage: number,
			stabDamage: number,
			coldDamage: number,
			fireDamage: number,
			lightningDamage: number,
			arcaneDamage: number,
			holyDamage: number,
			physicalResistance: number,
			coldResistance: number,
			fireResistance: number,
			lightningResistance: number,
			arcaneResistance: number,
			corruptResistance: number,
			degrees: number,
			lastX: number,
			lastY: number,
			flinchResistance: number,
			relocateToX: number,
			relocateToY: number,
			busyCastingAbility: boolean,
			talkingToNpc: string,
			isFemale: boolean
		};
		behaviors: __playerBehaviors<this>;
	}
	class __projectileBehaviors<InstType> {
		Bullet: IBulletBehaviorInstance<InstType>;
	}
	class projectile extends ISpriteInstance {
		instVars: {
			range: number,
			slashDamage: number,
			smashDamage: number,
			stabDamage: number,
			coldDamage: number,
			fireDamage: number,
			lightningDamage: number,
			arcaneDamage: number,
			holyDamage: number,
			corruptDamage: number,
			knockbackDistance: number,
			knockbackSpeed: number,
			piercing: boolean,
			enabled: boolean,
			isMelee: boolean
		};
		behaviors: __projectileBehaviors<this>;
	}
	class __npcBehaviors<InstType> {
		Solid: ISolidBehaviorInstance<InstType>;
		Persist: IBehaviorInstance<InstType>;
	}
	class npc extends ISpriteInstance {
		instVars: {
			simpleName: string,
			fullName: string,
			degrees: number,
			interactRange: number,
			dialogCounter: number,
			totalNumberOfDialogs: number,
			isMerchant: boolean,
			storeRange: number
		};
		behaviors: __npcBehaviors<this>;
	}
	class __man_shadowBehaviors<InstType> {
		Persist: IBehaviorInstance<InstType>;
	}
	class man_shadow extends ISpriteInstance {
		instVars: {
			yValue: number
		};
		behaviors: __man_shadowBehaviors<this>;
	}
	class __goblinArcher_shadowBehaviors<InstType> {
		Persist: IBehaviorInstance<InstType>;
	}
	class goblinArcher_shadow extends ISpriteInstance {
		instVars: {
			yValue: number
		};
		behaviors: __goblinArcher_shadowBehaviors<this>;
	}
	class __goblinUnderling_shadowBehaviors<InstType> {
		Persist: IBehaviorInstance<InstType>;
	}
	class goblinUnderling_shadow extends ISpriteInstance {
		instVars: {
			yValue: number
		};
		behaviors: __goblinUnderling_shadowBehaviors<this>;
	}
	class __goblinWarlock_shadowBehaviors<InstType> {
		Persist: IBehaviorInstance<InstType>;
	}
	class goblinWarlock_shadow extends ISpriteInstance {
		instVars: {
			yValue: number
		};
		behaviors: __goblinWarlock_shadowBehaviors<this>;
	}
	class __man_crudeHelmet_gear_shadowBehaviors<InstType> {
		Persist: IBehaviorInstance<InstType>;
	}
	class man_crudeHelmet_gear_shadow extends ISpriteInstance {
		instVars: {
			yValue: number
		};
		behaviors: __man_crudeHelmet_gear_shadowBehaviors<this>;
	}
	class __man_headDefault_gear_shadowBehaviors<InstType> {
		Persist: IBehaviorInstance<InstType>;
	}
	class man_headDefault_gear_shadow extends ISpriteInstance {
		instVars: {
			yValue: number
		};
		behaviors: __man_headDefault_gear_shadowBehaviors<this>;
	}
	class __man_leggings_gear_shadowBehaviors<InstType> {
		Persist: IBehaviorInstance<InstType>;
	}
	class man_leggings_gear_shadow extends ISpriteInstance {
		instVars: {
			yValue: number
		};
		behaviors: __man_leggings_gear_shadowBehaviors<this>;
	}
	class __man_maraudersBracers_gear_shadowBehaviors<InstType> {
		Persist: IBehaviorInstance<InstType>;
	}
	class man_maraudersBracers_gear_shadow extends ISpriteInstance {
		instVars: {
			yValue: number
		};
		behaviors: __man_maraudersBracers_gear_shadowBehaviors<this>;
	}
	class __man_maraudersStraps_gear_shadowBehaviors<InstType> {
		Persist: IBehaviorInstance<InstType>;
	}
	class man_maraudersStraps_gear_shadow extends ISpriteInstance {
		instVars: {
			yValue: number
		};
		behaviors: __man_maraudersStraps_gear_shadowBehaviors<this>;
	}
	class __man_ornateShield_gear_shadowBehaviors<InstType> {
		Persist: IBehaviorInstance<InstType>;
	}
	class man_ornateShield_gear_shadow extends ISpriteInstance {
		instVars: {
			yValue: number
		};
		behaviors: __man_ornateShield_gear_shadowBehaviors<this>;
	}
	class __man_simpleGloves_gear_shadowBehaviors<InstType> {
		Persist: IBehaviorInstance<InstType>;
	}
	class man_simpleGloves_gear_shadow extends ISpriteInstance {
		instVars: {
			yValue: number
		};
		behaviors: __man_simpleGloves_gear_shadowBehaviors<this>;
	}
	class __man_simpleHelmet_gear_shadowBehaviors<InstType> {
		Persist: IBehaviorInstance<InstType>;
	}
	class man_simpleHelmet_gear_shadow extends ISpriteInstance {
		instVars: {
			yValue: number
		};
		behaviors: __man_simpleHelmet_gear_shadowBehaviors<this>;
	}
	class __man_simpleMace_gear_shadowBehaviors<InstType> {
		Persist: IBehaviorInstance<InstType>;
	}
	class man_simpleMace_gear_shadow extends ISpriteInstance {
		instVars: {
			yValue: number
		};
		behaviors: __man_simpleMace_gear_shadowBehaviors<this>;
	}
	class __man_simpleShield_gear_shadowBehaviors<InstType> {
		Persist: IBehaviorInstance<InstType>;
	}
	class man_simpleShield_gear_shadow extends ISpriteInstance {
		instVars: {
			yValue: number
		};
		behaviors: __man_simpleShield_gear_shadowBehaviors<this>;
	}
	class __man_simpleShirt_gear_shadowBehaviors<InstType> {
		Persist: IBehaviorInstance<InstType>;
	}
	class man_simpleShirt_gear_shadow extends ISpriteInstance {
		instVars: {
			yValue: number
		};
		behaviors: __man_simpleShirt_gear_shadowBehaviors<this>;
	}
	class __man_simpleSword_gear_shadowBehaviors<InstType> {
		Persist: IBehaviorInstance<InstType>;
	}
	class man_simpleSword_gear_shadow extends ISpriteInstance {
		instVars: {
			yValue: number
		};
		behaviors: __man_simpleSword_gear_shadowBehaviors<this>;
	}
	class __man_strappedBoots_gear_shadowBehaviors<InstType> {
		Persist: IBehaviorInstance<InstType>;
	}
	class man_strappedBoots_gear_shadow extends ISpriteInstance {
		instVars: {
			yValue: number
		};
		behaviors: __man_strappedBoots_gear_shadowBehaviors<this>;
	}
	class __guide_shadowBehaviors<InstType> {
		Persist: IBehaviorInstance<InstType>;
	}
	class guide_shadow extends ISpriteInstance {
		instVars: {
			yValue: number
		};
		behaviors: __guide_shadowBehaviors<this>;
	}
	class __farmhouse_shadowBehaviors<InstType> {
		Persist: IBehaviorInstance<InstType>;
	}
	class farmhouse_shadow extends ISpriteInstance {
		instVars: {
			yValue: number
		};
		behaviors: __farmhouse_shadowBehaviors<this>;
	}
	class __farmhouseTree_shadowBehaviors<InstType> {
		Persist: IBehaviorInstance<InstType>;
	}
	class farmhouseTree_shadow extends ISpriteInstance {
		instVars: {
			yValue: number
		};
		behaviors: __farmhouseTree_shadowBehaviors<this>;
	}
	class __fenceHorizontal_shadowBehaviors<InstType> {
		Persist: IBehaviorInstance<InstType>;
	}
	class fenceHorizontal_shadow extends ISpriteInstance {
		instVars: {
			yValue: number
		};
		behaviors: __fenceHorizontal_shadowBehaviors<this>;
	}
	class __fencePatchedHorizontal_shadowBehaviors<InstType> {
		Persist: IBehaviorInstance<InstType>;
	}
	class fencePatchedHorizontal_shadow extends ISpriteInstance {
		instVars: {
			yValue: number
		};
		behaviors: __fencePatchedHorizontal_shadowBehaviors<this>;
	}
	class __fenceVertical_shadowBehaviors<InstType> {
		Persist: IBehaviorInstance<InstType>;
	}
	class fenceVertical_shadow extends ISpriteInstance {
		instVars: {
			yValue: number
		};
		behaviors: __fenceVertical_shadowBehaviors<this>;
	}
	class __cottageExterior_shadowBehaviors<InstType> {
		Persist: IBehaviorInstance<InstType>;
	}
	class cottageExterior_shadow extends ISpriteInstance {
		instVars: {
			yValue: number
		};
		behaviors: __cottageExterior_shadowBehaviors<this>;
	}
	class __windmillExterior_shadowBehaviors<InstType> {
		Persist: IBehaviorInstance<InstType>;
	}
	class windmillExterior_shadow extends ISpriteInstance {
		instVars: {
			yValue: number
		};
		behaviors: __windmillExterior_shadowBehaviors<this>;
	}
	class __windmillFan_shadowBehaviors<InstType> {
		Persist: IBehaviorInstance<InstType>;
	}
	class windmillFan_shadow extends ISpriteInstance {
		instVars: {
			yValue: number
		};
		behaviors: __windmillFan_shadowBehaviors<this>;
	}
	class __cart_shadowBehaviors<InstType> {
		Persist: IBehaviorInstance<InstType>;
	}
	class cart_shadow extends ISpriteInstance {
		instVars: {
			yValue: number
		};
		behaviors: __cart_shadowBehaviors<this>;
	}
	class __fenceRight_shadowBehaviors<InstType> {
		Persist: IBehaviorInstance<InstType>;
	}
	class fenceRight_shadow extends ISpriteInstance {
		instVars: {
			yValue: number
		};
		behaviors: __fenceRight_shadowBehaviors<this>;
	}
	class __fencePatchedLeft_shadowBehaviors<InstType> {
		Persist: IBehaviorInstance<InstType>;
	}
	class fencePatchedLeft_shadow extends ISpriteInstance {
		instVars: {
			yValue: number
		};
		behaviors: __fencePatchedLeft_shadowBehaviors<this>;
	}
	class __fenceLeft_shadowBehaviors<InstType> {
		Persist: IBehaviorInstance<InstType>;
	}
	class fenceLeft_shadow extends ISpriteInstance {
		instVars: {
			yValue: number
		};
		behaviors: __fenceLeft_shadowBehaviors<this>;
	}
	class __fencePatchedRight_shadowBehaviors<InstType> {
		Persist: IBehaviorInstance<InstType>;
	}
	class fencePatchedRight_shadow extends ISpriteInstance {
		instVars: {
			yValue: number
		};
		behaviors: __fencePatchedRight_shadowBehaviors<this>;
	}
	class __man_legsDefault_gear_shadowBehaviors<InstType> {
		Persist: IBehaviorInstance<InstType>;
	}
	class man_legsDefault_gear_shadow extends ISpriteInstance {
		instVars: {
			yValue: number
		};
		behaviors: __man_legsDefault_gear_shadowBehaviors<this>;
	}
	class __man_simplePants_gear_shadowBehaviors<InstType> {
		Persist: IBehaviorInstance<InstType>;
	}
	class man_simplePants_gear_shadow extends ISpriteInstance {
		instVars: {
			yValue: number
		};
		behaviors: __man_simplePants_gear_shadowBehaviors<this>;
	}
	class __crossbowBolt_shadowBehaviors<InstType> {
		Persist: IBehaviorInstance<InstType>;
	}
	class crossbowBolt_shadow extends ISpriteInstance {
		instVars: {
			yValue: number
		};
		behaviors: __crossbowBolt_shadowBehaviors<this>;
	}
	class __lightningOrb_shadowBehaviors<InstType> {
		Persist: IBehaviorInstance<InstType>;
	}
	class lightningOrb_shadow extends ISpriteInstance {
		instVars: {
			yValue: number
		};
		behaviors: __lightningOrb_shadowBehaviors<this>;
	}
	class __longhouse_shadowBehaviors<InstType> {
		Persist: IBehaviorInstance<InstType>;
	}
	class longhouse_shadow extends ISpriteInstance {
		instVars: {
			yValue: number
		};
		behaviors: __longhouse_shadowBehaviors<this>;
	}
	class __table_shadowBehaviors<InstType> {
		Persist: IBehaviorInstance<InstType>;
	}
	class table_shadow extends ISpriteInstance {
		instVars: {
			yValue: number
		};
		behaviors: __table_shadowBehaviors<this>;
	}
	class __woodenChest_shadowBehaviors<InstType> {
		Persist: IBehaviorInstance<InstType>;
	}
	class woodenChest_shadow extends ISpriteInstance {
		instVars: {
			yValue: number
		};
		behaviors: __woodenChest_shadowBehaviors<this>;
	}
	class __merchant_shadowBehaviors<InstType> {
		Persist: IBehaviorInstance<InstType>;
	}
	class merchant_shadow extends ISpriteInstance {
		instVars: {
			yValue: number
		};
		behaviors: __merchant_shadowBehaviors<this>;
	}
	class __guide_portraitBehaviors<InstType> {
		Tween: ITweenBehaviorInstance<InstType>;
	}
	class guide_portrait extends ISpriteInstance {
		behaviors: __guide_portraitBehaviors<this>;
	}
	class __merchant_portraitBehaviors<InstType> {
		Tween: ITweenBehaviorInstance<InstType>;
	}
	class merchant_portrait extends ISpriteInstance {
		behaviors: __merchant_portraitBehaviors<this>;
	}
	class __fenceHorizontalBehaviors<InstType> {
		Solid: ISolidBehaviorInstance<InstType>;
	}
	class fenceHorizontal extends ISpriteInstance {
		instVars: {
			yValue: number,
			doNotCreateShadow: boolean
		};
		behaviors: __fenceHorizontalBehaviors<this>;
	}
	class __fencePatchedHorizontalBehaviors<InstType> {
		Solid: ISolidBehaviorInstance<InstType>;
	}
	class fencePatchedHorizontal extends ISpriteInstance {
		instVars: {
			yValue: number,
			doNotCreateShadow: boolean
		};
		behaviors: __fencePatchedHorizontalBehaviors<this>;
	}
	class __farmhouseBehaviors<InstType> {
		Solid: ISolidBehaviorInstance<InstType>;
	}
	class farmhouse extends ISpriteInstance {
		instVars: {
			yValue: number,
			doNotCreateShadow: boolean
		};
		behaviors: __farmhouseBehaviors<this>;
	}
	class __farmhouseTreeBehaviors<InstType> {
		Solid: ISolidBehaviorInstance<InstType>;
	}
	class farmhouseTree extends ISpriteInstance {
		instVars: {
			yValue: number,
			doNotCreateShadow: boolean
		};
		behaviors: __farmhouseTreeBehaviors<this>;
	}
	class __fenceVerticalBehaviors<InstType> {
		Solid: ISolidBehaviorInstance<InstType>;
	}
	class fenceVertical extends ISpriteInstance {
		instVars: {
			yValue: number,
			doNotCreateShadow: boolean
		};
		behaviors: __fenceVerticalBehaviors<this>;
	}
	class cottageDoor extends ISpriteInstance {
		instVars: {
			relocateToX: number,
			relocateToY: number,
			interactRange: number,
			layout: string,
			leftbbox: number,
			rightbbox: number,
			topbbox: number,
			bottombbox: number
		};
	}
	class __cottageExteriorBehaviors<InstType> {
		Solid: ISolidBehaviorInstance<InstType>;
	}
	class cottageExterior extends ISpriteInstance {
		instVars: {
			yValue: number,
			doNotCreateShadow: boolean
		};
		behaviors: __cottageExteriorBehaviors<this>;
	}
	class cottageInterior extends ISpriteInstance {
	}
	class __cottagePropsBehaviors<InstType> {
		Solid: ISolidBehaviorInstance<InstType>;
	}
	class cottageProps extends ISpriteInstance {
		instVars: {
			yValue: number
		};
		behaviors: __cottagePropsBehaviors<this>;
	}
	class windmillDoor extends ISpriteInstance {
		instVars: {
			relocateToX: number,
			relocateToY: number,
			interactRange: number,
			layout: string,
			leftbbox: number,
			rightbbox: number,
			topbbox: number,
			bottombbox: number
		};
	}
	class __windmillExteriorBehaviors<InstType> {
		Solid: ISolidBehaviorInstance<InstType>;
	}
	class windmillExterior extends ISpriteInstance {
		instVars: {
			yValue: number,
			doNotCreateShadow: boolean
		};
		behaviors: __windmillExteriorBehaviors<this>;
	}
	class windmillFan extends ISpriteInstance {
		instVars: {
			doNotCreateShadow: boolean
		};
	}
	class windmillFloorLevel extends ISpriteInstance {
	}
	class windmillInterior extends ISpriteInstance {
	}
	class windmillLowerStairs extends ISpriteInstance {
		instVars: {
			relocateToX: number,
			relocateToY: number,
			interactRange: number,
			layout: string,
			leftbbox: number,
			rightbbox: number,
			topbbox: number,
			bottombbox: number
		};
	}
	class windmillUpperStairs extends ISpriteInstance {
		instVars: {
			relocateToX: number,
			relocateToY: number,
			interactRange: number,
			layout: string,
			leftbbox: number,
			rightbbox: number,
			topbbox: number,
			bottombbox: number
		};
	}
	class __cartBehaviors<InstType> {
		Solid: ISolidBehaviorInstance<InstType>;
	}
	class cart extends ISpriteInstance {
		instVars: {
			yValue: number,
			doNotCreateShadow: boolean
		};
		behaviors: __cartBehaviors<this>;
	}
	class __fencePatchedLeftBehaviors<InstType> {
		Solid: ISolidBehaviorInstance<InstType>;
	}
	class fencePatchedLeft extends ISpriteInstance {
		instVars: {
			yValue: number,
			doNotCreateShadow: boolean
		};
		behaviors: __fencePatchedLeftBehaviors<this>;
	}
	class __fenceRightBehaviors<InstType> {
		Solid: ISolidBehaviorInstance<InstType>;
	}
	class fenceRight extends ISpriteInstance {
		instVars: {
			yValue: number,
			doNotCreateShadow: boolean
		};
		behaviors: __fenceRightBehaviors<this>;
	}
	class __fenceLeftBehaviors<InstType> {
		Solid: ISolidBehaviorInstance<InstType>;
	}
	class fenceLeft extends ISpriteInstance {
		instVars: {
			yValue: number,
			doNotCreateShadow: boolean
		};
		behaviors: __fenceLeftBehaviors<this>;
	}
	class __fencePatchedRightBehaviors<InstType> {
		Solid: ISolidBehaviorInstance<InstType>;
	}
	class fencePatchedRight extends ISpriteInstance {
		instVars: {
			yValue: number,
			doNotCreateShadow: boolean
		};
		behaviors: __fencePatchedRightBehaviors<this>;
	}
	class __longhouseBehaviors<InstType> {
		Solid: ISolidBehaviorInstance<InstType>;
	}
	class longhouse extends ISpriteInstance {
		instVars: {
			yValue: number,
			doNotCreateShadow: boolean
		};
		behaviors: __longhouseBehaviors<this>;
	}
	class __tableBehaviors<InstType> {
		Solid: ISolidBehaviorInstance<InstType>;
	}
	class table extends ISpriteInstance {
		instVars: {
			yValue: number,
			doNotCreateShadow: boolean
		};
		behaviors: __tableBehaviors<this>;
	}
	class __woodenChestBehaviors<InstType> {
		Solid: ISolidBehaviorInstance<InstType>;
		Persist: IBehaviorInstance<InstType>;
	}
	class woodenChest extends ISpriteInstance {
		instVars: {
			yValue: number,
			doNotCreateShadow: boolean
		};
		behaviors: __woodenChestBehaviors<this>;
	}
	class cursor extends ISpriteInstance {
	}
	class lightningOrb extends ISpriteInstance {
		instVars: {
			yValue: number,
			doNotCreateShadow: boolean
		};
	}
	class crossbowBolt extends ISpriteInstance {
		instVars: {
			yValue: number,
			doNotCreateShadow: boolean
		};
	}
	class gear extends ISpriteInstance {
		instVars: {
			type: string
		};
	}
	class mainHand extends ISpriteInstance {
	}
	class offHand extends ISpriteInstance {
	}
	class __lootBehaviors<InstType> {
		Tween: ITweenBehaviorInstance<InstType>;
		Persist: IBehaviorInstance<InstType>;
	}
	class loot extends ISpriteInstance {
		instVars: {
			identifier: number,
			pickupRangeBonus: number,
			destinationX: number,
			destinationY: number,
			level: number,
			value: number,
			simpleName: string,
			fullName: string,
			type: string,
			lore: string,
			mods: string,
			classRestrictions: string,
			sound: string
		};
		behaviors: __lootBehaviors<this>;
	}
	class chest extends ISpriteInstance {
	}
	class __itemBehaviors<InstType> {
		DragDrop: IDragDropBehaviorInstance<InstType>;
		Tween: ITweenBehaviorInstance<InstType>;
	}
	class item extends ISpriteInstance {
		instVars: {
			identifier: number,
			level: number,
			value: number,
			simpleName: string,
			fullName: string,
			type: string,
			lore: string,
			mods: string,
			classRestrictions: string,
			sound: string
		};
		behaviors: __itemBehaviors<this>;
	}
	class invalidLocation extends ISpriteInstance {
	}
	class legs extends ISpriteInstance {
	}
	class head extends ISpriteInstance {
	}
	class hands extends ISpriteInstance {
	}
	class __enemyBodyBehaviors<InstType> {
		Tween: ITweenBehaviorInstance<InstType>;
		Persist: IBehaviorInstance<InstType>;
	}
	class enemyBody extends ISpriteInstance {
		behaviors: __enemyBodyBehaviors<this>;
	}
	class body extends ISpriteInstance {
	}
	class feet extends ISpriteInstance {
	}
	class sortable extends ISpriteInstance {
		instVars: {
			yValue: number
		};
	}
	class __propBehaviors<InstType> {
		Solid: ISolidBehaviorInstance<InstType>;
	}
	class prop extends ISpriteInstance {
		behaviors: __propBehaviors<this>;
	}
	class background extends ITiledBackgroundInstance {
	}
	class placeholder extends ISpriteInstance {
	}
	class queriedArray extends IArrayInstance {
	}
	class __shadowBehaviors<InstType> {
		Persist: IBehaviorInstance<InstType>;
	}
	class shadow extends ISpriteInstance {
		behaviors: __shadowBehaviors<this>;
	}
	class hasShadow extends ISpriteInstance {
		instVars: {
			doNotCreateShadow: boolean
		};
	}
	class __npcBodyBehaviors<InstType> {
		Persist: IBehaviorInstance<InstType>;
	}
	class npcBody extends ISpriteInstance {
		behaviors: __npcBodyBehaviors<this>;
	}
	class __portraitBehaviors<InstType> {
		Tween: ITweenBehaviorInstance<InstType>;
	}
	class portrait extends ISpriteInstance {
		behaviors: __portraitBehaviors<this>;
	}
	class __statueBehaviors<InstType> {
		Anchor: IAnchorBehaviorInstance<InstType>;
		DragDrop: IDragDropBehaviorInstance<InstType>;
		Tween: ITweenBehaviorInstance<InstType>;
	}
	class statue extends ISpriteInstance {
		instVars: {
			originalX: number,
			originalY: number
		};
		behaviors: __statueBehaviors<this>;
	}
	class tooltipText extends ITextInstance {
	}
	class orb extends ITiledBackgroundInstance {
	}
	class ability extends ISpriteInstance {
	}
	class _9PatchInvalidLocations extends IWorldInstance {
	}
	class textButtons extends ITextInstance {
		instVars: {
			originalX: number,
			originalY: number,
			originalFaceSize: number
		};
	}
	class comparisonTooltipText extends ITextInstance {
	}
	class door extends ISpriteInstance {
		instVars: {
			relocateToX: number,
			relocateToY: number,
			interactRange: number,
			layout: string,
			leftbbox: number,
			rightbbox: number,
			topbbox: number,
			bottombbox: number
		};
	}
	class __anchorTiledBackgroundBehaviors<InstType> {
		Anchor: IAnchorBehaviorInstance<InstType>;
	}
	class anchorTiledBackground extends ITiledBackgroundInstance {
		behaviors: __anchorTiledBackgroundBehaviors<this>;
	}
	class __anchorTextBehaviors<InstType> {
		Anchor: IAnchorBehaviorInstance<InstType>;
	}
	class anchorText extends ITextInstance {
		behaviors: __anchorTextBehaviors<this>;
	}
	class checkbox extends ISpriteInstance {
	}
	class __lootChestBehaviors<InstType> {
		Persist: IBehaviorInstance<InstType>;
	}
	class lootChest extends ISpriteInstance {
		behaviors: __lootChestBehaviors<this>;
	}

}