# GitHub Actions workflow to deploy the contents of the website folder to GitHub Pages on new tag push
name: Deploy to GitHub Pages

on:
  push:
    tags:
      - '*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      pages: write
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload website folder
        uses: actions/upload-pages-artifact@v3
        with:
          path: website

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

      - name: Check if tag is three-digit version
        id: tagcheck
        run: |
          if [[ "${GITHUB_REF##*/}" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "is_release_tag=true" >> $GITHUB_OUTPUT
          else
            echo "is_release_tag=false" >> $GITHUB_OUTPUT
          fi

      - name: Create GitHub Release
        if: steps.tagcheck.outputs.is_release_tag == 'true'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          body: |
            Play now at https://daggerquest.com/

            Read the patch notes at https://daggerquest.com/news/patch-notes-${{ github.ref_name }}
